/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: playlist4changes.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "playlist4changes.pb-c.h"
void   change_info__init
                     (ChangeInfo         *message)
{
  static const ChangeInfo init_value = CHANGE_INFO__INIT;
  *message = init_value;
}
size_t change_info__get_packed_size
                     (const ChangeInfo *message)
{
  assert(message->base.descriptor == &change_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t change_info__pack
                     (const ChangeInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &change_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t change_info__pack_to_buffer
                     (const ChangeInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &change_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChangeInfo *
       change_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChangeInfo *)
     protobuf_c_message_unpack (&change_info__descriptor,
                                allocator, len, data);
}
void   change_info__free_unpacked
                     (ChangeInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &change_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   delta__init
                     (Delta         *message)
{
  static const Delta init_value = DELTA__INIT;
  *message = init_value;
}
size_t delta__get_packed_size
                     (const Delta *message)
{
  assert(message->base.descriptor == &delta__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t delta__pack
                     (const Delta *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &delta__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t delta__pack_to_buffer
                     (const Delta *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &delta__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Delta *
       delta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Delta *)
     protobuf_c_message_unpack (&delta__descriptor,
                                allocator, len, data);
}
void   delta__free_unpacked
                     (Delta *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &delta__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   merge__init
                     (Merge         *message)
{
  static const Merge init_value = MERGE__INIT;
  *message = init_value;
}
size_t merge__get_packed_size
                     (const Merge *message)
{
  assert(message->base.descriptor == &merge__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t merge__pack
                     (const Merge *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &merge__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t merge__pack_to_buffer
                     (const Merge *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &merge__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Merge *
       merge__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Merge *)
     protobuf_c_message_unpack (&merge__descriptor,
                                allocator, len, data);
}
void   merge__free_unpacked
                     (Merge *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &merge__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   change_set__init
                     (ChangeSet         *message)
{
  static const ChangeSet init_value = CHANGE_SET__INIT;
  *message = init_value;
}
size_t change_set__get_packed_size
                     (const ChangeSet *message)
{
  assert(message->base.descriptor == &change_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t change_set__pack
                     (const ChangeSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &change_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t change_set__pack_to_buffer
                     (const ChangeSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &change_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChangeSet *
       change_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChangeSet *)
     protobuf_c_message_unpack (&change_set__descriptor,
                                allocator, len, data);
}
void   change_set__free_unpacked
                     (ChangeSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &change_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   revision_tagged_change_set__init
                     (RevisionTaggedChangeSet         *message)
{
  static const RevisionTaggedChangeSet init_value = REVISION_TAGGED_CHANGE_SET__INIT;
  *message = init_value;
}
size_t revision_tagged_change_set__get_packed_size
                     (const RevisionTaggedChangeSet *message)
{
  assert(message->base.descriptor == &revision_tagged_change_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t revision_tagged_change_set__pack
                     (const RevisionTaggedChangeSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &revision_tagged_change_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t revision_tagged_change_set__pack_to_buffer
                     (const RevisionTaggedChangeSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &revision_tagged_change_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RevisionTaggedChangeSet *
       revision_tagged_change_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RevisionTaggedChangeSet *)
     protobuf_c_message_unpack (&revision_tagged_change_set__descriptor,
                                allocator, len, data);
}
void   revision_tagged_change_set__free_unpacked
                     (RevisionTaggedChangeSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &revision_tagged_change_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   diff__init
                     (Diff         *message)
{
  static const Diff init_value = DIFF__INIT;
  *message = init_value;
}
size_t diff__get_packed_size
                     (const Diff *message)
{
  assert(message->base.descriptor == &diff__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t diff__pack
                     (const Diff *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &diff__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t diff__pack_to_buffer
                     (const Diff *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &diff__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Diff *
       diff__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Diff *)
     protobuf_c_message_unpack (&diff__descriptor,
                                allocator, len, data);
}
void   diff__free_unpacked
                     (Diff *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &diff__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   list_dump__init
                     (ListDump         *message)
{
  static const ListDump init_value = LIST_DUMP__INIT;
  *message = init_value;
}
size_t list_dump__get_packed_size
                     (const ListDump *message)
{
  assert(message->base.descriptor == &list_dump__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t list_dump__pack
                     (const ListDump *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &list_dump__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t list_dump__pack_to_buffer
                     (const ListDump *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &list_dump__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ListDump *
       list_dump__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ListDump *)
     protobuf_c_message_unpack (&list_dump__descriptor,
                                allocator, len, data);
}
void   list_dump__free_unpacked
                     (ListDump *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &list_dump__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   list_changes__init
                     (ListChanges         *message)
{
  static const ListChanges init_value = LIST_CHANGES__INIT;
  *message = init_value;
}
size_t list_changes__get_packed_size
                     (const ListChanges *message)
{
  assert(message->base.descriptor == &list_changes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t list_changes__pack
                     (const ListChanges *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &list_changes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t list_changes__pack_to_buffer
                     (const ListChanges *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &list_changes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ListChanges *
       list_changes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ListChanges *)
     protobuf_c_message_unpack (&list_changes__descriptor,
                                allocator, len, data);
}
void   list_changes__free_unpacked
                     (ListChanges *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &list_changes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   selected_list_content__init
                     (SelectedListContent         *message)
{
  static const SelectedListContent init_value = SELECTED_LIST_CONTENT__INIT;
  *message = init_value;
}
size_t selected_list_content__get_packed_size
                     (const SelectedListContent *message)
{
  assert(message->base.descriptor == &selected_list_content__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t selected_list_content__pack
                     (const SelectedListContent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &selected_list_content__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t selected_list_content__pack_to_buffer
                     (const SelectedListContent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &selected_list_content__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SelectedListContent *
       selected_list_content__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SelectedListContent *)
     protobuf_c_message_unpack (&selected_list_content__descriptor,
                                allocator, len, data);
}
void   selected_list_content__free_unpacked
                     (SelectedListContent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &selected_list_content__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor change_info__field_descriptors[8] =
{
  {
    "user",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ChangeInfo, user),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ChangeInfo, has_timestamp),
    offsetof(ChangeInfo, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "admin",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ChangeInfo, has_admin),
    offsetof(ChangeInfo, admin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "undo",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ChangeInfo, has_undo),
    offsetof(ChangeInfo, undo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "redo",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ChangeInfo, has_redo),
    offsetof(ChangeInfo, redo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "merge",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ChangeInfo, has_merge),
    offsetof(ChangeInfo, merge),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "compressed",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ChangeInfo, has_compressed),
    offsetof(ChangeInfo, compressed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "migration",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ChangeInfo, has_migration),
    offsetof(ChangeInfo, migration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned change_info__field_indices_by_name[] = {
  2,   /* field[2] = admin */
  6,   /* field[6] = compressed */
  5,   /* field[5] = merge */
  7,   /* field[7] = migration */
  4,   /* field[4] = redo */
  1,   /* field[1] = timestamp */
  3,   /* field[3] = undo */
  0,   /* field[0] = user */
};
static const ProtobufCIntRange change_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor change_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ChangeInfo",
  "ChangeInfo",
  "ChangeInfo",
  "",
  sizeof(ChangeInfo),
  8,
  change_info__field_descriptors,
  change_info__field_indices_by_name,
  1,  change_info__number_ranges,
  (ProtobufCMessageInit) change_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor delta__field_descriptors[3] =
{
  {
    "base_version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Delta, has_base_version),
    offsetof(Delta, base_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ops",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Delta, n_ops),
    offsetof(Delta, ops),
    &op__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Delta, info),
    &change_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned delta__field_indices_by_name[] = {
  0,   /* field[0] = base_version */
  2,   /* field[2] = info */
  1,   /* field[1] = ops */
};
static const ProtobufCIntRange delta__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor delta__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Delta",
  "Delta",
  "Delta",
  "",
  sizeof(Delta),
  3,
  delta__field_descriptors,
  delta__field_indices_by_name,
  2,  delta__number_ranges,
  (ProtobufCMessageInit) delta__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor merge__field_descriptors[3] =
{
  {
    "base_version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Merge, has_base_version),
    offsetof(Merge, base_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "merge_version",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Merge, has_merge_version),
    offsetof(Merge, merge_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Merge, info),
    &change_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned merge__field_indices_by_name[] = {
  0,   /* field[0] = base_version */
  2,   /* field[2] = info */
  1,   /* field[1] = merge_version */
};
static const ProtobufCIntRange merge__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor merge__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Merge",
  "Merge",
  "Merge",
  "",
  sizeof(Merge),
  3,
  merge__field_descriptors,
  merge__field_indices_by_name,
  2,  merge__number_ranges,
  (ProtobufCMessageInit) merge__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue change_set__kind__enum_values_by_number[3] =
{
  { "KIND_UNKNOWN", "CHANGE_SET__KIND__KIND_UNKNOWN", 0 },
  { "DELTA", "CHANGE_SET__KIND__DELTA", 2 },
  { "MERGE", "CHANGE_SET__KIND__MERGE", 3 },
};
static const ProtobufCIntRange change_set__kind__value_ranges[] = {
{0, 0},{2, 1},{0, 3}
};
static const ProtobufCEnumValueIndex change_set__kind__enum_values_by_name[3] =
{
  { "DELTA", 1 },
  { "KIND_UNKNOWN", 0 },
  { "MERGE", 2 },
};
const ProtobufCEnumDescriptor change_set__kind__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ChangeSet.Kind",
  "Kind",
  "ChangeSet__Kind",
  "",
  3,
  change_set__kind__enum_values_by_number,
  3,
  change_set__kind__enum_values_by_name,
  2,
  change_set__kind__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor change_set__field_descriptors[3] =
{
  {
    "kind",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ChangeSet, has_kind),
    offsetof(ChangeSet, kind),
    &change_set__kind__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delta",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ChangeSet, delta),
    &delta__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "merge",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ChangeSet, merge),
    &merge__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned change_set__field_indices_by_name[] = {
  1,   /* field[1] = delta */
  0,   /* field[0] = kind */
  2,   /* field[2] = merge */
};
static const ProtobufCIntRange change_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor change_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ChangeSet",
  "ChangeSet",
  "ChangeSet",
  "",
  sizeof(ChangeSet),
  3,
  change_set__field_descriptors,
  change_set__field_indices_by_name,
  1,  change_set__number_ranges,
  (ProtobufCMessageInit) change_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor revision_tagged_change_set__field_descriptors[2] =
{
  {
    "revision",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RevisionTaggedChangeSet, has_revision),
    offsetof(RevisionTaggedChangeSet, revision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "change_set",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RevisionTaggedChangeSet, change_set),
    &change_set__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned revision_tagged_change_set__field_indices_by_name[] = {
  1,   /* field[1] = change_set */
  0,   /* field[0] = revision */
};
static const ProtobufCIntRange revision_tagged_change_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor revision_tagged_change_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RevisionTaggedChangeSet",
  "RevisionTaggedChangeSet",
  "RevisionTaggedChangeSet",
  "",
  sizeof(RevisionTaggedChangeSet),
  2,
  revision_tagged_change_set__field_descriptors,
  revision_tagged_change_set__field_indices_by_name,
  1,  revision_tagged_change_set__number_ranges,
  (ProtobufCMessageInit) revision_tagged_change_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor diff__field_descriptors[3] =
{
  {
    "from_revision",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Diff, has_from_revision),
    offsetof(Diff, from_revision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ops",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Diff, n_ops),
    offsetof(Diff, ops),
    &op__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "to_revision",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Diff, has_to_revision),
    offsetof(Diff, to_revision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned diff__field_indices_by_name[] = {
  0,   /* field[0] = from_revision */
  1,   /* field[1] = ops */
  2,   /* field[2] = to_revision */
};
static const ProtobufCIntRange diff__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor diff__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Diff",
  "Diff",
  "Diff",
  "",
  sizeof(Diff),
  3,
  diff__field_descriptors,
  diff__field_indices_by_name,
  1,  diff__number_ranges,
  (ProtobufCMessageInit) diff__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor list_dump__field_descriptors[6] =
{
  {
    "latestRevision",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ListDump, has_latestrevision),
    offsetof(ListDump, latestrevision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ListDump, has_length),
    offsetof(ListDump, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributes",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ListDump, attributes),
    &list_attributes__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "checksum",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ListDump, checksum),
    &list_checksum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contents",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ListDump, contents),
    &list_items__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pendingDeltas",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ListDump, n_pendingdeltas),
    offsetof(ListDump, pendingdeltas),
    &delta__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned list_dump__field_indices_by_name[] = {
  2,   /* field[2] = attributes */
  3,   /* field[3] = checksum */
  4,   /* field[4] = contents */
  0,   /* field[0] = latestRevision */
  1,   /* field[1] = length */
  5,   /* field[5] = pendingDeltas */
};
static const ProtobufCIntRange list_dump__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 7, 5 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor list_dump__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ListDump",
  "ListDump",
  "ListDump",
  "",
  sizeof(ListDump),
  6,
  list_dump__field_descriptors,
  list_dump__field_indices_by_name,
  2,  list_dump__number_ranges,
  (ProtobufCMessageInit) list_dump__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor list_changes__field_descriptors[6] =
{
  {
    "baseRevision",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ListChanges, has_baserevision),
    offsetof(ListChanges, baserevision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deltas",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ListChanges, n_deltas),
    offsetof(ListChanges, deltas),
    &delta__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wantResultingRevisions",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ListChanges, has_wantresultingrevisions),
    offsetof(ListChanges, wantresultingrevisions),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wantSyncResult",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ListChanges, has_wantsyncresult),
    offsetof(ListChanges, wantsyncresult),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dump",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ListChanges, dump),
    &list_dump__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonces",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ListChanges, n_nonces),
    offsetof(ListChanges, nonces),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned list_changes__field_indices_by_name[] = {
  0,   /* field[0] = baseRevision */
  1,   /* field[1] = deltas */
  4,   /* field[4] = dump */
  5,   /* field[5] = nonces */
  2,   /* field[2] = wantResultingRevisions */
  3,   /* field[3] = wantSyncResult */
};
static const ProtobufCIntRange list_changes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor list_changes__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ListChanges",
  "ListChanges",
  "ListChanges",
  "",
  sizeof(ListChanges),
  6,
  list_changes__field_descriptors,
  list_changes__field_indices_by_name,
  1,  list_changes__number_ranges,
  (ProtobufCMessageInit) list_changes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor selected_list_content__field_descriptors[14] =
{
  {
    "revision",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(SelectedListContent, has_revision),
    offsetof(SelectedListContent, revision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SelectedListContent, has_length),
    offsetof(SelectedListContent, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributes",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SelectedListContent, attributes),
    &list_attributes__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "checksum",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SelectedListContent, checksum),
    &list_checksum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contents",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SelectedListContent, contents),
    &list_items__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "diff",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SelectedListContent, diff),
    &diff__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "syncResult",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SelectedListContent, syncresult),
    &diff__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resultingRevisions",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(SelectedListContent, n_resultingrevisions),
    offsetof(SelectedListContent, resultingrevisions),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "multipleHeads",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SelectedListContent, has_multipleheads),
    offsetof(SelectedListContent, multipleheads),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "upToDate",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SelectedListContent, has_uptodate),
    offsetof(SelectedListContent, uptodate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resolveAction",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SelectedListContent, n_resolveaction),
    offsetof(SelectedListContent, resolveaction),
    &client_resolve_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "issues",
    13,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SelectedListContent, n_issues),
    offsetof(SelectedListContent, issues),
    &client_issue__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonces",
    14,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SelectedListContent, n_nonces),
    offsetof(SelectedListContent, nonces),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owner_username",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SelectedListContent, owner_username),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned selected_list_content__field_indices_by_name[] = {
  2,   /* field[2] = attributes */
  3,   /* field[3] = checksum */
  4,   /* field[4] = contents */
  5,   /* field[5] = diff */
  11,   /* field[11] = issues */
  1,   /* field[1] = length */
  8,   /* field[8] = multipleHeads */
  12,   /* field[12] = nonces */
  13,   /* field[13] = owner_username */
  10,   /* field[10] = resolveAction */
  7,   /* field[7] = resultingRevisions */
  0,   /* field[0] = revision */
  6,   /* field[6] = syncResult */
  9,   /* field[9] = upToDate */
};
static const ProtobufCIntRange selected_list_content__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 12, 10 },
  { 16, 13 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor selected_list_content__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SelectedListContent",
  "SelectedListContent",
  "SelectedListContent",
  "",
  sizeof(SelectedListContent),
  14,
  selected_list_content__field_descriptors,
  selected_list_content__field_indices_by_name,
  3,  selected_list_content__number_ranges,
  (ProtobufCMessageInit) selected_list_content__init,
  NULL,NULL,NULL    /* reserved[123] */
};
