/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: playlist4changes.proto */

#ifndef PROTOBUF_C_playlist4changes_2eproto__INCLUDED
#define PROTOBUF_C_playlist4changes_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "playlist4ops.pb-c.h"
#include "playlist4meta.pb-c.h"
#include "playlist4content.pb-c.h"
#include "playlist4issues.pb-c.h"

typedef struct ChangeInfo ChangeInfo;
typedef struct Delta Delta;
typedef struct Merge Merge;
typedef struct ChangeSet ChangeSet;
typedef struct RevisionTaggedChangeSet RevisionTaggedChangeSet;
typedef struct Diff Diff;
typedef struct ListDump ListDump;
typedef struct ListChanges ListChanges;
typedef struct SelectedListContent SelectedListContent;


/* --- enums --- */

typedef enum _ChangeSet__Kind {
  CHANGE_SET__KIND__KIND_UNKNOWN = 0,
  CHANGE_SET__KIND__DELTA = 2,
  CHANGE_SET__KIND__MERGE = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CHANGE_SET__KIND)
} ChangeSet__Kind;

/* --- messages --- */

struct  ChangeInfo
{
  ProtobufCMessage base;
  char *user;
  protobuf_c_boolean has_timestamp;
  int32_t timestamp;
  protobuf_c_boolean has_admin;
  protobuf_c_boolean admin;
  protobuf_c_boolean has_undo;
  protobuf_c_boolean undo;
  protobuf_c_boolean has_redo;
  protobuf_c_boolean redo;
  protobuf_c_boolean has_merge;
  protobuf_c_boolean merge;
  protobuf_c_boolean has_compressed;
  protobuf_c_boolean compressed;
  protobuf_c_boolean has_migration;
  protobuf_c_boolean migration;
};
#define CHANGE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&change_info__descriptor) \
    , NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  Delta
{
  ProtobufCMessage base;
  protobuf_c_boolean has_base_version;
  ProtobufCBinaryData base_version;
  size_t n_ops;
  Op **ops;
  ChangeInfo *info;
};
#define DELTA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&delta__descriptor) \
    , 0, {0,NULL}, 0,NULL, NULL }


struct  Merge
{
  ProtobufCMessage base;
  protobuf_c_boolean has_base_version;
  ProtobufCBinaryData base_version;
  protobuf_c_boolean has_merge_version;
  ProtobufCBinaryData merge_version;
  ChangeInfo *info;
};
#define MERGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&merge__descriptor) \
    , 0, {0,NULL}, 0, {0,NULL}, NULL }


struct  ChangeSet
{
  ProtobufCMessage base;
  protobuf_c_boolean has_kind;
  ChangeSet__Kind kind;
  Delta *delta;
  Merge *merge;
};
#define CHANGE_SET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&change_set__descriptor) \
    , 0, CHANGE_SET__KIND__KIND_UNKNOWN, NULL, NULL }


struct  RevisionTaggedChangeSet
{
  ProtobufCMessage base;
  protobuf_c_boolean has_revision;
  ProtobufCBinaryData revision;
  ChangeSet *change_set;
};
#define REVISION_TAGGED_CHANGE_SET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&revision_tagged_change_set__descriptor) \
    , 0, {0,NULL}, NULL }


struct  Diff
{
  ProtobufCMessage base;
  protobuf_c_boolean has_from_revision;
  ProtobufCBinaryData from_revision;
  size_t n_ops;
  Op **ops;
  protobuf_c_boolean has_to_revision;
  ProtobufCBinaryData to_revision;
};
#define DIFF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&diff__descriptor) \
    , 0, {0,NULL}, 0,NULL, 0, {0,NULL} }


struct  ListDump
{
  ProtobufCMessage base;
  protobuf_c_boolean has_latestrevision;
  ProtobufCBinaryData latestrevision;
  protobuf_c_boolean has_length;
  int32_t length;
  ListAttributes *attributes;
  ListChecksum *checksum;
  ListItems *contents;
  size_t n_pendingdeltas;
  Delta **pendingdeltas;
};
#define LIST_DUMP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&list_dump__descriptor) \
    , 0, {0,NULL}, 0, 0, NULL, NULL, NULL, 0,NULL }


struct  ListChanges
{
  ProtobufCMessage base;
  protobuf_c_boolean has_baserevision;
  ProtobufCBinaryData baserevision;
  size_t n_deltas;
  Delta **deltas;
  protobuf_c_boolean has_wantresultingrevisions;
  protobuf_c_boolean wantresultingrevisions;
  protobuf_c_boolean has_wantsyncresult;
  protobuf_c_boolean wantsyncresult;
  ListDump *dump;
  size_t n_nonces;
  int32_t *nonces;
};
#define LIST_CHANGES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&list_changes__descriptor) \
    , 0, {0,NULL}, 0,NULL, 0, 0, 0, 0, NULL, 0,NULL }


struct  SelectedListContent
{
  ProtobufCMessage base;
  protobuf_c_boolean has_revision;
  ProtobufCBinaryData revision;
  protobuf_c_boolean has_length;
  int32_t length;
  ListAttributes *attributes;
  ListChecksum *checksum;
  ListItems *contents;
  Diff *diff;
  Diff *syncresult;
  size_t n_resultingrevisions;
  ProtobufCBinaryData *resultingrevisions;
  protobuf_c_boolean has_multipleheads;
  protobuf_c_boolean multipleheads;
  protobuf_c_boolean has_uptodate;
  protobuf_c_boolean uptodate;
  size_t n_resolveaction;
  ClientResolveAction **resolveaction;
  size_t n_issues;
  ClientIssue **issues;
  size_t n_nonces;
  int32_t *nonces;
  char *owner_username;
};
#define SELECTED_LIST_CONTENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&selected_list_content__descriptor) \
    , 0, {0,NULL}, 0, 0, NULL, NULL, NULL, NULL, NULL, 0,NULL, 0, 0, 0, 0, 0,NULL, 0,NULL, 0,NULL, NULL }


/* ChangeInfo methods */
void   change_info__init
                     (ChangeInfo         *message);
size_t change_info__get_packed_size
                     (const ChangeInfo   *message);
size_t change_info__pack
                     (const ChangeInfo   *message,
                      uint8_t             *out);
size_t change_info__pack_to_buffer
                     (const ChangeInfo   *message,
                      ProtobufCBuffer     *buffer);
ChangeInfo *
       change_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   change_info__free_unpacked
                     (ChangeInfo *message,
                      ProtobufCAllocator *allocator);
/* Delta methods */
void   delta__init
                     (Delta         *message);
size_t delta__get_packed_size
                     (const Delta   *message);
size_t delta__pack
                     (const Delta   *message,
                      uint8_t             *out);
size_t delta__pack_to_buffer
                     (const Delta   *message,
                      ProtobufCBuffer     *buffer);
Delta *
       delta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   delta__free_unpacked
                     (Delta *message,
                      ProtobufCAllocator *allocator);
/* Merge methods */
void   merge__init
                     (Merge         *message);
size_t merge__get_packed_size
                     (const Merge   *message);
size_t merge__pack
                     (const Merge   *message,
                      uint8_t             *out);
size_t merge__pack_to_buffer
                     (const Merge   *message,
                      ProtobufCBuffer     *buffer);
Merge *
       merge__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   merge__free_unpacked
                     (Merge *message,
                      ProtobufCAllocator *allocator);
/* ChangeSet methods */
void   change_set__init
                     (ChangeSet         *message);
size_t change_set__get_packed_size
                     (const ChangeSet   *message);
size_t change_set__pack
                     (const ChangeSet   *message,
                      uint8_t             *out);
size_t change_set__pack_to_buffer
                     (const ChangeSet   *message,
                      ProtobufCBuffer     *buffer);
ChangeSet *
       change_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   change_set__free_unpacked
                     (ChangeSet *message,
                      ProtobufCAllocator *allocator);
/* RevisionTaggedChangeSet methods */
void   revision_tagged_change_set__init
                     (RevisionTaggedChangeSet         *message);
size_t revision_tagged_change_set__get_packed_size
                     (const RevisionTaggedChangeSet   *message);
size_t revision_tagged_change_set__pack
                     (const RevisionTaggedChangeSet   *message,
                      uint8_t             *out);
size_t revision_tagged_change_set__pack_to_buffer
                     (const RevisionTaggedChangeSet   *message,
                      ProtobufCBuffer     *buffer);
RevisionTaggedChangeSet *
       revision_tagged_change_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   revision_tagged_change_set__free_unpacked
                     (RevisionTaggedChangeSet *message,
                      ProtobufCAllocator *allocator);
/* Diff methods */
void   diff__init
                     (Diff         *message);
size_t diff__get_packed_size
                     (const Diff   *message);
size_t diff__pack
                     (const Diff   *message,
                      uint8_t             *out);
size_t diff__pack_to_buffer
                     (const Diff   *message,
                      ProtobufCBuffer     *buffer);
Diff *
       diff__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   diff__free_unpacked
                     (Diff *message,
                      ProtobufCAllocator *allocator);
/* ListDump methods */
void   list_dump__init
                     (ListDump         *message);
size_t list_dump__get_packed_size
                     (const ListDump   *message);
size_t list_dump__pack
                     (const ListDump   *message,
                      uint8_t             *out);
size_t list_dump__pack_to_buffer
                     (const ListDump   *message,
                      ProtobufCBuffer     *buffer);
ListDump *
       list_dump__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   list_dump__free_unpacked
                     (ListDump *message,
                      ProtobufCAllocator *allocator);
/* ListChanges methods */
void   list_changes__init
                     (ListChanges         *message);
size_t list_changes__get_packed_size
                     (const ListChanges   *message);
size_t list_changes__pack
                     (const ListChanges   *message,
                      uint8_t             *out);
size_t list_changes__pack_to_buffer
                     (const ListChanges   *message,
                      ProtobufCBuffer     *buffer);
ListChanges *
       list_changes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   list_changes__free_unpacked
                     (ListChanges *message,
                      ProtobufCAllocator *allocator);
/* SelectedListContent methods */
void   selected_list_content__init
                     (SelectedListContent         *message);
size_t selected_list_content__get_packed_size
                     (const SelectedListContent   *message);
size_t selected_list_content__pack
                     (const SelectedListContent   *message,
                      uint8_t             *out);
size_t selected_list_content__pack_to_buffer
                     (const SelectedListContent   *message,
                      ProtobufCBuffer     *buffer);
SelectedListContent *
       selected_list_content__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   selected_list_content__free_unpacked
                     (SelectedListContent *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ChangeInfo_Closure)
                 (const ChangeInfo *message,
                  void *closure_data);
typedef void (*Delta_Closure)
                 (const Delta *message,
                  void *closure_data);
typedef void (*Merge_Closure)
                 (const Merge *message,
                  void *closure_data);
typedef void (*ChangeSet_Closure)
                 (const ChangeSet *message,
                  void *closure_data);
typedef void (*RevisionTaggedChangeSet_Closure)
                 (const RevisionTaggedChangeSet *message,
                  void *closure_data);
typedef void (*Diff_Closure)
                 (const Diff *message,
                  void *closure_data);
typedef void (*ListDump_Closure)
                 (const ListDump *message,
                  void *closure_data);
typedef void (*ListChanges_Closure)
                 (const ListChanges *message,
                  void *closure_data);
typedef void (*SelectedListContent_Closure)
                 (const SelectedListContent *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor change_info__descriptor;
extern const ProtobufCMessageDescriptor delta__descriptor;
extern const ProtobufCMessageDescriptor merge__descriptor;
extern const ProtobufCMessageDescriptor change_set__descriptor;
extern const ProtobufCEnumDescriptor    change_set__kind__descriptor;
extern const ProtobufCMessageDescriptor revision_tagged_change_set__descriptor;
extern const ProtobufCMessageDescriptor diff__descriptor;
extern const ProtobufCMessageDescriptor list_dump__descriptor;
extern const ProtobufCMessageDescriptor list_changes__descriptor;
extern const ProtobufCMessageDescriptor selected_list_content__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_playlist4changes_2eproto__INCLUDED */
