/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: playlist4meta.proto */

#ifndef PROTOBUF_C_playlist4meta_2eproto__INCLUDED
#define PROTOBUF_C_playlist4meta_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct ListChecksum ListChecksum;
typedef struct DownloadFormat DownloadFormat;
typedef struct ListAttributes ListAttributes;
typedef struct ItemAttributes ItemAttributes;
typedef struct StringAttribute StringAttribute;
typedef struct StringAttributes StringAttributes;


/* --- enums --- */

typedef enum _DownloadFormat__Codec {
  DOWNLOAD_FORMAT__CODEC__CODEC_UNKNOWN = 0,
  DOWNLOAD_FORMAT__CODEC__OGG_VORBIS = 1,
  DOWNLOAD_FORMAT__CODEC__FLAC = 2,
  DOWNLOAD_FORMAT__CODEC__MPEG_1_LAYER_3 = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DOWNLOAD_FORMAT__CODEC)
} DownloadFormat__Codec;

/* --- messages --- */

struct  ListChecksum
{
  ProtobufCMessage base;
  protobuf_c_boolean has_version;
  int32_t version;
  protobuf_c_boolean has_sha1;
  ProtobufCBinaryData sha1;
};
#define LIST_CHECKSUM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&list_checksum__descriptor) \
    , 0, 0, 0, {0,NULL} }


struct  DownloadFormat
{
  ProtobufCMessage base;
  protobuf_c_boolean has_codec;
  DownloadFormat__Codec codec;
};
#define DOWNLOAD_FORMAT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&download_format__descriptor) \
    , 0, DOWNLOAD_FORMAT__CODEC__CODEC_UNKNOWN }


struct  ListAttributes
{
  ProtobufCMessage base;
  char *name;
  char *description;
  protobuf_c_boolean has_picture;
  ProtobufCBinaryData picture;
  protobuf_c_boolean has_collaborative;
  protobuf_c_boolean collaborative;
  char *pl3_version;
  protobuf_c_boolean has_deleted_by_owner;
  protobuf_c_boolean deleted_by_owner;
  protobuf_c_boolean has_restricted_collaborative;
  protobuf_c_boolean restricted_collaborative;
  protobuf_c_boolean has_deprecated_client_id;
  int64_t deprecated_client_id;
  protobuf_c_boolean has_public_starred;
  protobuf_c_boolean public_starred;
  char *client_id;
};
#define LIST_ATTRIBUTES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&list_attributes__descriptor) \
    , NULL, NULL, 0, {0,NULL}, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, NULL }


struct  ItemAttributes
{
  ProtobufCMessage base;
  char *added_by;
  protobuf_c_boolean has_timestamp;
  int64_t timestamp;
  char *message;
  protobuf_c_boolean has_seen;
  protobuf_c_boolean seen;
  protobuf_c_boolean has_download_count;
  int64_t download_count;
  DownloadFormat *download_format;
  char *sevendigital_id;
  protobuf_c_boolean has_sevendigital_left;
  int64_t sevendigital_left;
  protobuf_c_boolean has_seen_at;
  int64_t seen_at;
  protobuf_c_boolean has_public_;
  protobuf_c_boolean public_;
};
#define ITEM_ATTRIBUTES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&item_attributes__descriptor) \
    , NULL, 0, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0 }


struct  StringAttribute
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define STRING_ATTRIBUTE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&string_attribute__descriptor) \
    , NULL, NULL }


struct  StringAttributes
{
  ProtobufCMessage base;
  size_t n_attribute;
  StringAttribute **attribute;
};
#define STRING_ATTRIBUTES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&string_attributes__descriptor) \
    , 0,NULL }


/* ListChecksum methods */
void   list_checksum__init
                     (ListChecksum         *message);
size_t list_checksum__get_packed_size
                     (const ListChecksum   *message);
size_t list_checksum__pack
                     (const ListChecksum   *message,
                      uint8_t             *out);
size_t list_checksum__pack_to_buffer
                     (const ListChecksum   *message,
                      ProtobufCBuffer     *buffer);
ListChecksum *
       list_checksum__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   list_checksum__free_unpacked
                     (ListChecksum *message,
                      ProtobufCAllocator *allocator);
/* DownloadFormat methods */
void   download_format__init
                     (DownloadFormat         *message);
size_t download_format__get_packed_size
                     (const DownloadFormat   *message);
size_t download_format__pack
                     (const DownloadFormat   *message,
                      uint8_t             *out);
size_t download_format__pack_to_buffer
                     (const DownloadFormat   *message,
                      ProtobufCBuffer     *buffer);
DownloadFormat *
       download_format__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   download_format__free_unpacked
                     (DownloadFormat *message,
                      ProtobufCAllocator *allocator);
/* ListAttributes methods */
void   list_attributes__init
                     (ListAttributes         *message);
size_t list_attributes__get_packed_size
                     (const ListAttributes   *message);
size_t list_attributes__pack
                     (const ListAttributes   *message,
                      uint8_t             *out);
size_t list_attributes__pack_to_buffer
                     (const ListAttributes   *message,
                      ProtobufCBuffer     *buffer);
ListAttributes *
       list_attributes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   list_attributes__free_unpacked
                     (ListAttributes *message,
                      ProtobufCAllocator *allocator);
/* ItemAttributes methods */
void   item_attributes__init
                     (ItemAttributes         *message);
size_t item_attributes__get_packed_size
                     (const ItemAttributes   *message);
size_t item_attributes__pack
                     (const ItemAttributes   *message,
                      uint8_t             *out);
size_t item_attributes__pack_to_buffer
                     (const ItemAttributes   *message,
                      ProtobufCBuffer     *buffer);
ItemAttributes *
       item_attributes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   item_attributes__free_unpacked
                     (ItemAttributes *message,
                      ProtobufCAllocator *allocator);
/* StringAttribute methods */
void   string_attribute__init
                     (StringAttribute         *message);
size_t string_attribute__get_packed_size
                     (const StringAttribute   *message);
size_t string_attribute__pack
                     (const StringAttribute   *message,
                      uint8_t             *out);
size_t string_attribute__pack_to_buffer
                     (const StringAttribute   *message,
                      ProtobufCBuffer     *buffer);
StringAttribute *
       string_attribute__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   string_attribute__free_unpacked
                     (StringAttribute *message,
                      ProtobufCAllocator *allocator);
/* StringAttributes methods */
void   string_attributes__init
                     (StringAttributes         *message);
size_t string_attributes__get_packed_size
                     (const StringAttributes   *message);
size_t string_attributes__pack
                     (const StringAttributes   *message,
                      uint8_t             *out);
size_t string_attributes__pack_to_buffer
                     (const StringAttributes   *message,
                      ProtobufCBuffer     *buffer);
StringAttributes *
       string_attributes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   string_attributes__free_unpacked
                     (StringAttributes *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ListChecksum_Closure)
                 (const ListChecksum *message,
                  void *closure_data);
typedef void (*DownloadFormat_Closure)
                 (const DownloadFormat *message,
                  void *closure_data);
typedef void (*ListAttributes_Closure)
                 (const ListAttributes *message,
                  void *closure_data);
typedef void (*ItemAttributes_Closure)
                 (const ItemAttributes *message,
                  void *closure_data);
typedef void (*StringAttribute_Closure)
                 (const StringAttribute *message,
                  void *closure_data);
typedef void (*StringAttributes_Closure)
                 (const StringAttributes *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor list_checksum__descriptor;
extern const ProtobufCMessageDescriptor download_format__descriptor;
extern const ProtobufCEnumDescriptor    download_format__codec__descriptor;
extern const ProtobufCMessageDescriptor list_attributes__descriptor;
extern const ProtobufCMessageDescriptor item_attributes__descriptor;
extern const ProtobufCMessageDescriptor string_attribute__descriptor;
extern const ProtobufCMessageDescriptor string_attributes__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_playlist4meta_2eproto__INCLUDED */
