/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: spirc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "spirc.pb-c.h"
void   frame__init
                     (Frame         *message)
{
  static const Frame init_value = FRAME__INIT;
  *message = init_value;
}
size_t frame__get_packed_size
                     (const Frame *message)
{
  assert(message->base.descriptor == &frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t frame__pack
                     (const Frame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t frame__pack_to_buffer
                     (const Frame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Frame *
       frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Frame *)
     protobuf_c_message_unpack (&frame__descriptor,
                                allocator, len, data);
}
void   frame__free_unpacked
                     (Frame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   device_state__init
                     (DeviceState         *message)
{
  static const DeviceState init_value = DEVICE_STATE__INIT;
  *message = init_value;
}
size_t device_state__get_packed_size
                     (const DeviceState *message)
{
  assert(message->base.descriptor == &device_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_state__pack
                     (const DeviceState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_state__pack_to_buffer
                     (const DeviceState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceState *
       device_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceState *)
     protobuf_c_message_unpack (&device_state__descriptor,
                                allocator, len, data);
}
void   device_state__free_unpacked
                     (DeviceState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   capability__init
                     (Capability         *message)
{
  static const Capability init_value = CAPABILITY__INIT;
  *message = init_value;
}
size_t capability__get_packed_size
                     (const Capability *message)
{
  assert(message->base.descriptor == &capability__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t capability__pack
                     (const Capability *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &capability__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t capability__pack_to_buffer
                     (const Capability *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &capability__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Capability *
       capability__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Capability *)
     protobuf_c_message_unpack (&capability__descriptor,
                                allocator, len, data);
}
void   capability__free_unpacked
                     (Capability *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &capability__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   goodbye__init
                     (Goodbye         *message)
{
  static const Goodbye init_value = GOODBYE__INIT;
  *message = init_value;
}
size_t goodbye__get_packed_size
                     (const Goodbye *message)
{
  assert(message->base.descriptor == &goodbye__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t goodbye__pack
                     (const Goodbye *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &goodbye__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t goodbye__pack_to_buffer
                     (const Goodbye *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &goodbye__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Goodbye *
       goodbye__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Goodbye *)
     protobuf_c_message_unpack (&goodbye__descriptor,
                                allocator, len, data);
}
void   goodbye__free_unpacked
                     (Goodbye *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &goodbye__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   state__init
                     (State         *message)
{
  static const State init_value = STATE__INIT;
  *message = init_value;
}
size_t state__get_packed_size
                     (const State *message)
{
  assert(message->base.descriptor == &state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t state__pack
                     (const State *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t state__pack_to_buffer
                     (const State *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
State *
       state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (State *)
     protobuf_c_message_unpack (&state__descriptor,
                                allocator, len, data);
}
void   state__free_unpacked
                     (State *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   track_ref__init
                     (TrackRef         *message)
{
  static const TrackRef init_value = TRACK_REF__INIT;
  *message = init_value;
}
size_t track_ref__get_packed_size
                     (const TrackRef *message)
{
  assert(message->base.descriptor == &track_ref__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t track_ref__pack
                     (const TrackRef *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &track_ref__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t track_ref__pack_to_buffer
                     (const TrackRef *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &track_ref__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrackRef *
       track_ref__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrackRef *)
     protobuf_c_message_unpack (&track_ref__descriptor,
                                allocator, len, data);
}
void   track_ref__free_unpacked
                     (TrackRef *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &track_ref__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ad__init
                     (Ad         *message)
{
  static const Ad init_value = AD__INIT;
  *message = init_value;
}
size_t ad__get_packed_size
                     (const Ad *message)
{
  assert(message->base.descriptor == &ad__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ad__pack
                     (const Ad *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ad__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ad__pack_to_buffer
                     (const Ad *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ad__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ad *
       ad__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ad *)
     protobuf_c_message_unpack (&ad__descriptor,
                                allocator, len, data);
}
void   ad__free_unpacked
                     (Ad *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ad__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   metadata__init
                     (Metadata         *message)
{
  static const Metadata init_value = METADATA__INIT;
  *message = init_value;
}
size_t metadata__get_packed_size
                     (const Metadata *message)
{
  assert(message->base.descriptor == &metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t metadata__pack
                     (const Metadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t metadata__pack_to_buffer
                     (const Metadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Metadata *
       metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Metadata *)
     protobuf_c_message_unpack (&metadata__descriptor,
                                allocator, len, data);
}
void   metadata__free_unpacked
                     (Metadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor frame__field_descriptors[15] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Frame, has_version),
    offsetof(Frame, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ident",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Frame, ident),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protocol_version",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Frame, protocol_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq_nr",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Frame, has_seq_nr),
    offsetof(Frame, seq_nr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "typ",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Frame, has_typ),
    offsetof(Frame, typ),
    &message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_state",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Frame, device_state),
    &device_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "goodbye",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Frame, goodbye),
    &goodbye__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Frame, state),
    &state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Frame, has_position),
    offsetof(Frame, position),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "volume",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Frame, has_volume),
    offsetof(Frame, volume),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state_update_id",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Frame, has_state_update_id),
    offsetof(Frame, state_update_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recipient",
    18,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Frame, n_recipient),
    offsetof(Frame, recipient),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "context_player_state",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Frame, has_context_player_state),
    offsetof(Frame, context_player_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_name",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Frame, new_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadata",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Frame, metadata),
    &metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned frame__field_indices_by_name[] = {
  12,   /* field[12] = context_player_state */
  5,   /* field[5] = device_state */
  6,   /* field[6] = goodbye */
  1,   /* field[1] = ident */
  14,   /* field[14] = metadata */
  13,   /* field[13] = new_name */
  8,   /* field[8] = position */
  2,   /* field[2] = protocol_version */
  11,   /* field[11] = recipient */
  3,   /* field[3] = seq_nr */
  7,   /* field[7] = state */
  10,   /* field[10] = state_update_id */
  4,   /* field[4] = typ */
  0,   /* field[0] = version */
  9,   /* field[9] = volume */
};
static const ProtobufCIntRange frame__number_ranges[5 + 1] =
{
  { 1, 0 },
  { 7, 5 },
  { 11, 6 },
  { 17, 10 },
  { 25, 14 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Frame",
  "Frame",
  "Frame",
  "",
  sizeof(Frame),
  15,
  frame__field_descriptors,
  frame__field_indices_by_name,
  5,  frame__number_ranges,
  (ProtobufCMessageInit) frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor device_state__field_descriptors[11] =
{
  {
    "sw_version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceState, sw_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_active",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DeviceState, has_is_active),
    offsetof(DeviceState, is_active),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "can_play",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DeviceState, has_can_play),
    offsetof(DeviceState, can_play),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "volume",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DeviceState, has_volume),
    offsetof(DeviceState, volume),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceState, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_code",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DeviceState, has_error_code),
    offsetof(DeviceState, error_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "became_active_at",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(DeviceState, has_became_active_at),
    offsetof(DeviceState, became_active_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_message",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceState, error_message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "capabilities",
    17,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DeviceState, n_capabilities),
    offsetof(DeviceState, capabilities),
    &capability__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "context_player_error",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceState, context_player_error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadata",
    25,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DeviceState, n_metadata),
    offsetof(DeviceState, metadata),
    &metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_state__field_indices_by_name[] = {
  6,   /* field[6] = became_active_at */
  2,   /* field[2] = can_play */
  8,   /* field[8] = capabilities */
  9,   /* field[9] = context_player_error */
  5,   /* field[5] = error_code */
  7,   /* field[7] = error_message */
  1,   /* field[1] = is_active */
  10,   /* field[10] = metadata */
  4,   /* field[4] = name */
  0,   /* field[0] = sw_version */
  3,   /* field[3] = volume */
};
static const ProtobufCIntRange device_state__number_ranges[4 + 1] =
{
  { 1, 0 },
  { 10, 1 },
  { 20, 9 },
  { 25, 10 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor device_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceState",
  "DeviceState",
  "DeviceState",
  "",
  sizeof(DeviceState),
  11,
  device_state__field_descriptors,
  device_state__field_indices_by_name,
  4,  device_state__number_ranges,
  (ProtobufCMessageInit) device_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor capability__field_descriptors[3] =
{
  {
    "typ",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Capability, has_typ),
    offsetof(Capability, typ),
    &capability_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "intValue",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Capability, n_intvalue),
    offsetof(Capability, intvalue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stringValue",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Capability, n_stringvalue),
    offsetof(Capability, stringvalue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned capability__field_indices_by_name[] = {
  1,   /* field[1] = intValue */
  2,   /* field[2] = stringValue */
  0,   /* field[0] = typ */
};
static const ProtobufCIntRange capability__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor capability__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Capability",
  "Capability",
  "Capability",
  "",
  sizeof(Capability),
  3,
  capability__field_descriptors,
  capability__field_indices_by_name,
  1,  capability__number_ranges,
  (ProtobufCMessageInit) capability__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor goodbye__field_descriptors[1] =
{
  {
    "reason",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Goodbye, reason),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned goodbye__field_indices_by_name[] = {
  0,   /* field[0] = reason */
};
static const ProtobufCIntRange goodbye__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor goodbye__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Goodbye",
  "Goodbye",
  "Goodbye",
  "",
  sizeof(Goodbye),
  1,
  goodbye__field_descriptors,
  goodbye__field_indices_by_name,
  1,  goodbye__number_ranges,
  (ProtobufCMessageInit) goodbye__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor state__field_descriptors[15] =
{
  {
    "context_uri",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(State, context_uri),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(State, has_index),
    offsetof(State, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_ms",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(State, has_position_ms),
    offsetof(State, position_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(State, has_status),
    offsetof(State, status),
    &play_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_measured_at",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(State, has_position_measured_at),
    offsetof(State, position_measured_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "context_description",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(State, context_description),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shuffle",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(State, has_shuffle),
    offsetof(State, shuffle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "repeat",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(State, has_repeat),
    offsetof(State, repeat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_command_ident",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(State, last_command_ident),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_command_msgid",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(State, has_last_command_msgid),
    offsetof(State, last_command_msgid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "playing_from_fallback",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(State, has_playing_from_fallback),
    offsetof(State, playing_from_fallback),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "row",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(State, has_row),
    offsetof(State, row),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "playing_track_index",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(State, has_playing_track_index),
    offsetof(State, playing_track_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "track",
    27,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(State, n_track),
    offsetof(State, track),
    &track_ref__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ad",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(State, ad),
    &ad__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned state__field_indices_by_name[] = {
  14,   /* field[14] = ad */
  5,   /* field[5] = context_description */
  0,   /* field[0] = context_uri */
  1,   /* field[1] = index */
  8,   /* field[8] = last_command_ident */
  9,   /* field[9] = last_command_msgid */
  10,   /* field[10] = playing_from_fallback */
  12,   /* field[12] = playing_track_index */
  4,   /* field[4] = position_measured_at */
  2,   /* field[2] = position_ms */
  7,   /* field[7] = repeat */
  11,   /* field[11] = row */
  6,   /* field[6] = shuffle */
  3,   /* field[3] = status */
  13,   /* field[13] = track */
};
static const ProtobufCIntRange state__number_ranges[5 + 1] =
{
  { 2, 0 },
  { 7, 4 },
  { 13, 6 },
  { 20, 8 },
  { 24, 10 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "State",
  "State",
  "State",
  "",
  sizeof(State),
  15,
  state__field_descriptors,
  state__field_indices_by_name,
  5,  state__number_ranges,
  (ProtobufCMessageInit) state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor track_ref__field_descriptors[4] =
{
  {
    "gid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(TrackRef, has_gid),
    offsetof(TrackRef, gid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uri",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TrackRef, uri),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "queued",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(TrackRef, has_queued),
    offsetof(TrackRef, queued),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "context",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TrackRef, context),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned track_ref__field_indices_by_name[] = {
  3,   /* field[3] = context */
  0,   /* field[0] = gid */
  2,   /* field[2] = queued */
  1,   /* field[1] = uri */
};
static const ProtobufCIntRange track_ref__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor track_ref__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TrackRef",
  "TrackRef",
  "TrackRef",
  "",
  sizeof(TrackRef),
  4,
  track_ref__field_descriptors,
  track_ref__field_indices_by_name,
  1,  track_ref__number_ranges,
  (ProtobufCMessageInit) track_ref__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ad__field_descriptors[9] =
{
  {
    "next",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ad, has_next),
    offsetof(Ad, next),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ogg_fid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Ad, has_ogg_fid),
    offsetof(Ad, ogg_fid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image_fid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Ad, has_image_fid),
    offsetof(Ad, image_fid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duration",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ad, has_duration),
    offsetof(Ad, duration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "click_url",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ad, click_url),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "impression_url",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ad, impression_url),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "product",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ad, product),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "advertiser",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ad, advertiser),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Ad, has_gid),
    offsetof(Ad, gid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ad__field_indices_by_name[] = {
  7,   /* field[7] = advertiser */
  4,   /* field[4] = click_url */
  3,   /* field[3] = duration */
  8,   /* field[8] = gid */
  2,   /* field[2] = image_fid */
  5,   /* field[5] = impression_url */
  0,   /* field[0] = next */
  1,   /* field[1] = ogg_fid */
  6,   /* field[6] = product */
};
static const ProtobufCIntRange ad__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor ad__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ad",
  "Ad",
  "Ad",
  "",
  sizeof(Ad),
  9,
  ad__field_descriptors,
  ad__field_indices_by_name,
  1,  ad__number_ranges,
  (ProtobufCMessageInit) ad__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor metadata__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Metadata, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadata",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Metadata, metadata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned metadata__field_indices_by_name[] = {
  1,   /* field[1] = metadata */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Metadata",
  "Metadata",
  "Metadata",
  "",
  sizeof(Metadata),
  2,
  metadata__field_descriptors,
  metadata__field_indices_by_name,
  1,  metadata__number_ranges,
  (ProtobufCMessageInit) metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue message_type__enum_values_by_number[21] =
{
  { "kMessageTypeHello", "MESSAGE_TYPE__kMessageTypeHello", 1 },
  { "kMessageTypeGoodbye", "MESSAGE_TYPE__kMessageTypeGoodbye", 2 },
  { "kMessageTypeProbe", "MESSAGE_TYPE__kMessageTypeProbe", 3 },
  { "kMessageTypeNotify", "MESSAGE_TYPE__kMessageTypeNotify", 10 },
  { "kMessageTypeLoad", "MESSAGE_TYPE__kMessageTypeLoad", 20 },
  { "kMessageTypePlay", "MESSAGE_TYPE__kMessageTypePlay", 21 },
  { "kMessageTypePause", "MESSAGE_TYPE__kMessageTypePause", 22 },
  { "kMessageTypePlayPause", "MESSAGE_TYPE__kMessageTypePlayPause", 23 },
  { "kMessageTypeSeek", "MESSAGE_TYPE__kMessageTypeSeek", 24 },
  { "kMessageTypePrev", "MESSAGE_TYPE__kMessageTypePrev", 25 },
  { "kMessageTypeNext", "MESSAGE_TYPE__kMessageTypeNext", 26 },
  { "kMessageTypeVolume", "MESSAGE_TYPE__kMessageTypeVolume", 27 },
  { "kMessageTypeShuffle", "MESSAGE_TYPE__kMessageTypeShuffle", 28 },
  { "kMessageTypeRepeat", "MESSAGE_TYPE__kMessageTypeRepeat", 29 },
  { "kMessageTypeVolumeDown", "MESSAGE_TYPE__kMessageTypeVolumeDown", 31 },
  { "kMessageTypeVolumeUp", "MESSAGE_TYPE__kMessageTypeVolumeUp", 32 },
  { "kMessageTypeReplace", "MESSAGE_TYPE__kMessageTypeReplace", 33 },
  { "kMessageTypeLogout", "MESSAGE_TYPE__kMessageTypeLogout", 34 },
  { "kMessageTypeAction", "MESSAGE_TYPE__kMessageTypeAction", 35 },
  { "kMessageTypeRename", "MESSAGE_TYPE__kMessageTypeRename", 36 },
  { "kMessageTypeUpdateMetadata", "MESSAGE_TYPE__kMessageTypeUpdateMetadata", 128 },
};
static const ProtobufCIntRange message_type__value_ranges[] = {
{1, 0},{10, 3},{20, 4},{31, 14},{128, 20},{0, 21}
};
static const ProtobufCEnumValueIndex message_type__enum_values_by_name[21] =
{
  { "kMessageTypeAction", 18 },
  { "kMessageTypeGoodbye", 1 },
  { "kMessageTypeHello", 0 },
  { "kMessageTypeLoad", 4 },
  { "kMessageTypeLogout", 17 },
  { "kMessageTypeNext", 10 },
  { "kMessageTypeNotify", 3 },
  { "kMessageTypePause", 6 },
  { "kMessageTypePlay", 5 },
  { "kMessageTypePlayPause", 7 },
  { "kMessageTypePrev", 9 },
  { "kMessageTypeProbe", 2 },
  { "kMessageTypeRename", 19 },
  { "kMessageTypeRepeat", 13 },
  { "kMessageTypeReplace", 16 },
  { "kMessageTypeSeek", 8 },
  { "kMessageTypeShuffle", 12 },
  { "kMessageTypeUpdateMetadata", 20 },
  { "kMessageTypeVolume", 11 },
  { "kMessageTypeVolumeDown", 14 },
  { "kMessageTypeVolumeUp", 15 },
};
const ProtobufCEnumDescriptor message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MessageType",
  "MessageType",
  "MessageType",
  "",
  21,
  message_type__enum_values_by_number,
  21,
  message_type__enum_values_by_name,
  5,
  message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue capability_type__enum_values_by_number[14] =
{
  { "kSupportedContexts", "CAPABILITY_TYPE__kSupportedContexts", 1 },
  { "kCanBePlayer", "CAPABILITY_TYPE__kCanBePlayer", 2 },
  { "kRestrictToLocal", "CAPABILITY_TYPE__kRestrictToLocal", 3 },
  { "kDeviceType", "CAPABILITY_TYPE__kDeviceType", 4 },
  { "kGaiaEqConnectId", "CAPABILITY_TYPE__kGaiaEqConnectId", 5 },
  { "kSupportsLogout", "CAPABILITY_TYPE__kSupportsLogout", 6 },
  { "kIsObservable", "CAPABILITY_TYPE__kIsObservable", 7 },
  { "kVolumeSteps", "CAPABILITY_TYPE__kVolumeSteps", 8 },
  { "kSupportedTypes", "CAPABILITY_TYPE__kSupportedTypes", 9 },
  { "kCommandAcks", "CAPABILITY_TYPE__kCommandAcks", 10 },
  { "kSupportsRename", "CAPABILITY_TYPE__kSupportsRename", 11 },
  { "kHidden", "CAPABILITY_TYPE__kHidden", 12 },
  { "kSupportsPlaylistV2", "CAPABILITY_TYPE__kSupportsPlaylistV2", 13 },
  { "kSupportsExternalEpisodes", "CAPABILITY_TYPE__kSupportsExternalEpisodes", 14 },
};
static const ProtobufCIntRange capability_type__value_ranges[] = {
{1, 0},{0, 14}
};
static const ProtobufCEnumValueIndex capability_type__enum_values_by_name[14] =
{
  { "kCanBePlayer", 1 },
  { "kCommandAcks", 9 },
  { "kDeviceType", 3 },
  { "kGaiaEqConnectId", 4 },
  { "kHidden", 11 },
  { "kIsObservable", 6 },
  { "kRestrictToLocal", 2 },
  { "kSupportedContexts", 0 },
  { "kSupportedTypes", 8 },
  { "kSupportsExternalEpisodes", 13 },
  { "kSupportsLogout", 5 },
  { "kSupportsPlaylistV2", 12 },
  { "kSupportsRename", 10 },
  { "kVolumeSteps", 7 },
};
const ProtobufCEnumDescriptor capability_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CapabilityType",
  "CapabilityType",
  "CapabilityType",
  "",
  14,
  capability_type__enum_values_by_number,
  14,
  capability_type__enum_values_by_name,
  1,
  capability_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue play_status__enum_values_by_number[4] =
{
  { "kPlayStatusStop", "PLAY_STATUS__kPlayStatusStop", 0 },
  { "kPlayStatusPlay", "PLAY_STATUS__kPlayStatusPlay", 1 },
  { "kPlayStatusPause", "PLAY_STATUS__kPlayStatusPause", 2 },
  { "kPlayStatusLoading", "PLAY_STATUS__kPlayStatusLoading", 3 },
};
static const ProtobufCIntRange play_status__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex play_status__enum_values_by_name[4] =
{
  { "kPlayStatusLoading", 3 },
  { "kPlayStatusPause", 2 },
  { "kPlayStatusPlay", 1 },
  { "kPlayStatusStop", 0 },
};
const ProtobufCEnumDescriptor play_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "PlayStatus",
  "PlayStatus",
  "PlayStatus",
  "",
  4,
  play_status__enum_values_by_number,
  4,
  play_status__enum_values_by_name,
  1,
  play_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
