/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: playlist4content.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "playlist4content.pb-c.h"
void   item__init
                     (Item         *message)
{
  static const Item init_value = ITEM__INIT;
  *message = init_value;
}
size_t item__get_packed_size
                     (const Item *message)
{
  assert(message->base.descriptor == &item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t item__pack
                     (const Item *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t item__pack_to_buffer
                     (const Item *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Item *
       item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Item *)
     protobuf_c_message_unpack (&item__descriptor,
                                allocator, len, data);
}
void   item__free_unpacked
                     (Item *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   list_items__init
                     (ListItems         *message)
{
  static const ListItems init_value = LIST_ITEMS__INIT;
  *message = init_value;
}
size_t list_items__get_packed_size
                     (const ListItems *message)
{
  assert(message->base.descriptor == &list_items__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t list_items__pack
                     (const ListItems *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &list_items__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t list_items__pack_to_buffer
                     (const ListItems *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &list_items__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ListItems *
       list_items__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ListItems *)
     protobuf_c_message_unpack (&list_items__descriptor,
                                allocator, len, data);
}
void   list_items__free_unpacked
                     (ListItems *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &list_items__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   content_range__init
                     (ContentRange         *message)
{
  static const ContentRange init_value = CONTENT_RANGE__INIT;
  *message = init_value;
}
size_t content_range__get_packed_size
                     (const ContentRange *message)
{
  assert(message->base.descriptor == &content_range__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t content_range__pack
                     (const ContentRange *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &content_range__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t content_range__pack_to_buffer
                     (const ContentRange *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &content_range__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ContentRange *
       content_range__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ContentRange *)
     protobuf_c_message_unpack (&content_range__descriptor,
                                allocator, len, data);
}
void   content_range__free_unpacked
                     (ContentRange *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &content_range__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   list_content_selection__init
                     (ListContentSelection         *message)
{
  static const ListContentSelection init_value = LIST_CONTENT_SELECTION__INIT;
  *message = init_value;
}
size_t list_content_selection__get_packed_size
                     (const ListContentSelection *message)
{
  assert(message->base.descriptor == &list_content_selection__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t list_content_selection__pack
                     (const ListContentSelection *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &list_content_selection__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t list_content_selection__pack_to_buffer
                     (const ListContentSelection *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &list_content_selection__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ListContentSelection *
       list_content_selection__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ListContentSelection *)
     protobuf_c_message_unpack (&list_content_selection__descriptor,
                                allocator, len, data);
}
void   list_content_selection__free_unpacked
                     (ListContentSelection *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &list_content_selection__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor item__field_descriptors[2] =
{
  {
    "uri",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Item, uri),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributes",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Item, attributes),
    &item_attributes__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned item__field_indices_by_name[] = {
  1,   /* field[1] = attributes */
  0,   /* field[0] = uri */
};
static const ProtobufCIntRange item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Item",
  "Item",
  "Item",
  "",
  sizeof(Item),
  2,
  item__field_descriptors,
  item__field_indices_by_name,
  1,  item__number_ranges,
  (ProtobufCMessageInit) item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor list_items__field_descriptors[3] =
{
  {
    "pos",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ListItems, has_pos),
    offsetof(ListItems, pos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "truncated",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ListItems, has_truncated),
    offsetof(ListItems, truncated),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "items",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ListItems, n_items),
    offsetof(ListItems, items),
    &item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned list_items__field_indices_by_name[] = {
  2,   /* field[2] = items */
  0,   /* field[0] = pos */
  1,   /* field[1] = truncated */
};
static const ProtobufCIntRange list_items__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor list_items__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ListItems",
  "ListItems",
  "ListItems",
  "",
  sizeof(ListItems),
  3,
  list_items__field_descriptors,
  list_items__field_indices_by_name,
  1,  list_items__number_ranges,
  (ProtobufCMessageInit) list_items__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor content_range__field_descriptors[2] =
{
  {
    "pos",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ContentRange, has_pos),
    offsetof(ContentRange, pos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ContentRange, has_length),
    offsetof(ContentRange, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned content_range__field_indices_by_name[] = {
  1,   /* field[1] = length */
  0,   /* field[0] = pos */
};
static const ProtobufCIntRange content_range__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor content_range__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ContentRange",
  "ContentRange",
  "ContentRange",
  "",
  sizeof(ContentRange),
  2,
  content_range__field_descriptors,
  content_range__field_indices_by_name,
  1,  content_range__number_ranges,
  (ProtobufCMessageInit) content_range__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor list_content_selection__field_descriptors[13] =
{
  {
    "wantRevision",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ListContentSelection, has_wantrevision),
    offsetof(ListContentSelection, wantrevision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wantLength",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ListContentSelection, has_wantlength),
    offsetof(ListContentSelection, wantlength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wantAttributes",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ListContentSelection, has_wantattributes),
    offsetof(ListContentSelection, wantattributes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wantChecksum",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ListContentSelection, has_wantchecksum),
    offsetof(ListContentSelection, wantchecksum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wantContent",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ListContentSelection, has_wantcontent),
    offsetof(ListContentSelection, wantcontent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contentRange",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ListContentSelection, contentrange),
    &content_range__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wantDiff",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ListContentSelection, has_wantdiff),
    offsetof(ListContentSelection, wantdiff),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baseRevision",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ListContentSelection, has_baserevision),
    offsetof(ListContentSelection, baserevision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hintRevision",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ListContentSelection, has_hintrevision),
    offsetof(ListContentSelection, hintrevision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wantNothingIfUpToDate",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ListContentSelection, has_wantnothingifuptodate),
    offsetof(ListContentSelection, wantnothingifuptodate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wantResolveAction",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ListContentSelection, has_wantresolveaction),
    offsetof(ListContentSelection, wantresolveaction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "issues",
    13,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ListContentSelection, n_issues),
    offsetof(ListContentSelection, issues),
    &client_issue__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resolveAction",
    14,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ListContentSelection, n_resolveaction),
    offsetof(ListContentSelection, resolveaction),
    &client_resolve_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned list_content_selection__field_indices_by_name[] = {
  7,   /* field[7] = baseRevision */
  5,   /* field[5] = contentRange */
  8,   /* field[8] = hintRevision */
  11,   /* field[11] = issues */
  12,   /* field[12] = resolveAction */
  2,   /* field[2] = wantAttributes */
  3,   /* field[3] = wantChecksum */
  4,   /* field[4] = wantContent */
  6,   /* field[6] = wantDiff */
  1,   /* field[1] = wantLength */
  9,   /* field[9] = wantNothingIfUpToDate */
  10,   /* field[10] = wantResolveAction */
  0,   /* field[0] = wantRevision */
};
static const ProtobufCIntRange list_content_selection__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 12, 10 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor list_content_selection__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ListContentSelection",
  "ListContentSelection",
  "ListContentSelection",
  "",
  sizeof(ListContentSelection),
  13,
  list_content_selection__field_descriptors,
  list_content_selection__field_indices_by_name,
  2,  list_content_selection__number_ranges,
  (ProtobufCMessageInit) list_content_selection__init,
  NULL,NULL,NULL    /* reserved[123] */
};
