/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: playlist4ops.proto */

#ifndef PROTOBUF_C_playlist4ops_2eproto__INCLUDED
#define PROTOBUF_C_playlist4ops_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "playlist4meta.pb-c.h"
#include "playlist4content.pb-c.h"

typedef struct Add Add;
typedef struct Rem Rem;
typedef struct Mov Mov;
typedef struct ItemAttributesPartialState ItemAttributesPartialState;
typedef struct ListAttributesPartialState ListAttributesPartialState;
typedef struct UpdateItemAttributes UpdateItemAttributes;
typedef struct UpdateListAttributes UpdateListAttributes;
typedef struct Op Op;
typedef struct OpList OpList;


/* --- enums --- */

typedef enum _ItemAttributesPartialState__ItemAttributeKind {
  ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_UNKNOWN = 0,
  ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_ADDED_BY = 1,
  ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_TIMESTAMP = 2,
  ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_MESSAGE = 3,
  ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_SEEN = 4,
  ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_DOWNLOAD_COUNT = 5,
  ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_DOWNLOAD_FORMAT = 6,
  ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_SEVENDIGITAL_ID = 7,
  ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_SEVENDIGITAL_LEFT = 8,
  ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_SEEN_AT = 9,
  ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_PUBLIC = 10
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND)
} ItemAttributesPartialState__ItemAttributeKind;
typedef enum _ListAttributesPartialState__ListAttributeKind {
  LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND__LIST_UNKNOWN = 0,
  LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND__LIST_NAME = 1,
  LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND__LIST_DESCRIPTION = 2,
  LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND__LIST_PICTURE = 3,
  LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND__LIST_COLLABORATIVE = 4,
  LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND__LIST_PL3_VERSION = 5,
  LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND__LIST_DELETED_BY_OWNER = 6,
  LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND__LIST_RESTRICTED_COLLABORATIVE = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND)
} ListAttributesPartialState__ListAttributeKind;
typedef enum _Op__Kind {
  OP__KIND__KIND_UNKNOWN = 0,
  OP__KIND__ADD = 2,
  OP__KIND__REM = 3,
  OP__KIND__MOV = 4,
  OP__KIND__UPDATE_ITEM_ATTRIBUTES = 5,
  OP__KIND__UPDATE_LIST_ATTRIBUTES = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(OP__KIND)
} Op__Kind;

/* --- messages --- */

struct  Add
{
  ProtobufCMessage base;
  protobuf_c_boolean has_fromindex;
  int32_t fromindex;
  size_t n_items;
  Item **items;
  ListChecksum *list_checksum;
  protobuf_c_boolean has_addlast;
  protobuf_c_boolean addlast;
  protobuf_c_boolean has_addfirst;
  protobuf_c_boolean addfirst;
};
#define ADD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&add__descriptor) \
    , 0, 0, 0,NULL, NULL, 0, 0, 0, 0 }


struct  Rem
{
  ProtobufCMessage base;
  protobuf_c_boolean has_fromindex;
  int32_t fromindex;
  protobuf_c_boolean has_length;
  int32_t length;
  size_t n_items;
  Item **items;
  ListChecksum *list_checksum;
  ListChecksum *items_checksum;
  ListChecksum *uris_checksum;
  protobuf_c_boolean has_itemsaskey;
  protobuf_c_boolean itemsaskey;
};
#define REM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rem__descriptor) \
    , 0, 0, 0, 0, 0,NULL, NULL, NULL, NULL, 0, 0 }


struct  Mov
{
  ProtobufCMessage base;
  protobuf_c_boolean has_fromindex;
  int32_t fromindex;
  protobuf_c_boolean has_length;
  int32_t length;
  protobuf_c_boolean has_toindex;
  int32_t toindex;
  ListChecksum *list_checksum;
  ListChecksum *items_checksum;
  ListChecksum *uris_checksum;
};
#define MOV__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mov__descriptor) \
    , 0, 0, 0, 0, 0, 0, NULL, NULL, NULL }


struct  ItemAttributesPartialState
{
  ProtobufCMessage base;
  ItemAttributes *values;
  size_t n_no_value;
  ItemAttributesPartialState__ItemAttributeKind *no_value;
};
#define ITEM_ATTRIBUTES_PARTIAL_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&item_attributes_partial_state__descriptor) \
    , NULL, 0,NULL }


struct  ListAttributesPartialState
{
  ProtobufCMessage base;
  ListAttributes *values;
  size_t n_no_value;
  ListAttributesPartialState__ListAttributeKind *no_value;
};
#define LIST_ATTRIBUTES_PARTIAL_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&list_attributes_partial_state__descriptor) \
    , NULL, 0,NULL }


struct  UpdateItemAttributes
{
  ProtobufCMessage base;
  protobuf_c_boolean has_index;
  int32_t index;
  ItemAttributesPartialState *new_attributes;
  ItemAttributesPartialState *old_attributes;
  ListChecksum *list_checksum;
  ListChecksum *old_attributes_checksum;
};
#define UPDATE_ITEM_ATTRIBUTES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&update_item_attributes__descriptor) \
    , 0, 0, NULL, NULL, NULL, NULL }


struct  UpdateListAttributes
{
  ProtobufCMessage base;
  ListAttributesPartialState *new_attributes;
  ListAttributesPartialState *old_attributes;
  ListChecksum *list_checksum;
  ListChecksum *old_attributes_checksum;
};
#define UPDATE_LIST_ATTRIBUTES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&update_list_attributes__descriptor) \
    , NULL, NULL, NULL, NULL }


struct  Op
{
  ProtobufCMessage base;
  protobuf_c_boolean has_kind;
  Op__Kind kind;
  Add *add;
  Rem *rem;
  Mov *mov;
  UpdateItemAttributes *update_item_attributes;
  UpdateListAttributes *update_list_attributes;
};
#define OP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&op__descriptor) \
    , 0, OP__KIND__KIND_UNKNOWN, NULL, NULL, NULL, NULL, NULL }


struct  OpList
{
  ProtobufCMessage base;
  size_t n_ops;
  Op **ops;
};
#define OP_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&op_list__descriptor) \
    , 0,NULL }


/* Add methods */
void   add__init
                     (Add         *message);
size_t add__get_packed_size
                     (const Add   *message);
size_t add__pack
                     (const Add   *message,
                      uint8_t             *out);
size_t add__pack_to_buffer
                     (const Add   *message,
                      ProtobufCBuffer     *buffer);
Add *
       add__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   add__free_unpacked
                     (Add *message,
                      ProtobufCAllocator *allocator);
/* Rem methods */
void   rem__init
                     (Rem         *message);
size_t rem__get_packed_size
                     (const Rem   *message);
size_t rem__pack
                     (const Rem   *message,
                      uint8_t             *out);
size_t rem__pack_to_buffer
                     (const Rem   *message,
                      ProtobufCBuffer     *buffer);
Rem *
       rem__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rem__free_unpacked
                     (Rem *message,
                      ProtobufCAllocator *allocator);
/* Mov methods */
void   mov__init
                     (Mov         *message);
size_t mov__get_packed_size
                     (const Mov   *message);
size_t mov__pack
                     (const Mov   *message,
                      uint8_t             *out);
size_t mov__pack_to_buffer
                     (const Mov   *message,
                      ProtobufCBuffer     *buffer);
Mov *
       mov__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mov__free_unpacked
                     (Mov *message,
                      ProtobufCAllocator *allocator);
/* ItemAttributesPartialState methods */
void   item_attributes_partial_state__init
                     (ItemAttributesPartialState         *message);
size_t item_attributes_partial_state__get_packed_size
                     (const ItemAttributesPartialState   *message);
size_t item_attributes_partial_state__pack
                     (const ItemAttributesPartialState   *message,
                      uint8_t             *out);
size_t item_attributes_partial_state__pack_to_buffer
                     (const ItemAttributesPartialState   *message,
                      ProtobufCBuffer     *buffer);
ItemAttributesPartialState *
       item_attributes_partial_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   item_attributes_partial_state__free_unpacked
                     (ItemAttributesPartialState *message,
                      ProtobufCAllocator *allocator);
/* ListAttributesPartialState methods */
void   list_attributes_partial_state__init
                     (ListAttributesPartialState         *message);
size_t list_attributes_partial_state__get_packed_size
                     (const ListAttributesPartialState   *message);
size_t list_attributes_partial_state__pack
                     (const ListAttributesPartialState   *message,
                      uint8_t             *out);
size_t list_attributes_partial_state__pack_to_buffer
                     (const ListAttributesPartialState   *message,
                      ProtobufCBuffer     *buffer);
ListAttributesPartialState *
       list_attributes_partial_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   list_attributes_partial_state__free_unpacked
                     (ListAttributesPartialState *message,
                      ProtobufCAllocator *allocator);
/* UpdateItemAttributes methods */
void   update_item_attributes__init
                     (UpdateItemAttributes         *message);
size_t update_item_attributes__get_packed_size
                     (const UpdateItemAttributes   *message);
size_t update_item_attributes__pack
                     (const UpdateItemAttributes   *message,
                      uint8_t             *out);
size_t update_item_attributes__pack_to_buffer
                     (const UpdateItemAttributes   *message,
                      ProtobufCBuffer     *buffer);
UpdateItemAttributes *
       update_item_attributes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   update_item_attributes__free_unpacked
                     (UpdateItemAttributes *message,
                      ProtobufCAllocator *allocator);
/* UpdateListAttributes methods */
void   update_list_attributes__init
                     (UpdateListAttributes         *message);
size_t update_list_attributes__get_packed_size
                     (const UpdateListAttributes   *message);
size_t update_list_attributes__pack
                     (const UpdateListAttributes   *message,
                      uint8_t             *out);
size_t update_list_attributes__pack_to_buffer
                     (const UpdateListAttributes   *message,
                      ProtobufCBuffer     *buffer);
UpdateListAttributes *
       update_list_attributes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   update_list_attributes__free_unpacked
                     (UpdateListAttributes *message,
                      ProtobufCAllocator *allocator);
/* Op methods */
void   op__init
                     (Op         *message);
size_t op__get_packed_size
                     (const Op   *message);
size_t op__pack
                     (const Op   *message,
                      uint8_t             *out);
size_t op__pack_to_buffer
                     (const Op   *message,
                      ProtobufCBuffer     *buffer);
Op *
       op__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   op__free_unpacked
                     (Op *message,
                      ProtobufCAllocator *allocator);
/* OpList methods */
void   op_list__init
                     (OpList         *message);
size_t op_list__get_packed_size
                     (const OpList   *message);
size_t op_list__pack
                     (const OpList   *message,
                      uint8_t             *out);
size_t op_list__pack_to_buffer
                     (const OpList   *message,
                      ProtobufCBuffer     *buffer);
OpList *
       op_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   op_list__free_unpacked
                     (OpList *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Add_Closure)
                 (const Add *message,
                  void *closure_data);
typedef void (*Rem_Closure)
                 (const Rem *message,
                  void *closure_data);
typedef void (*Mov_Closure)
                 (const Mov *message,
                  void *closure_data);
typedef void (*ItemAttributesPartialState_Closure)
                 (const ItemAttributesPartialState *message,
                  void *closure_data);
typedef void (*ListAttributesPartialState_Closure)
                 (const ListAttributesPartialState *message,
                  void *closure_data);
typedef void (*UpdateItemAttributes_Closure)
                 (const UpdateItemAttributes *message,
                  void *closure_data);
typedef void (*UpdateListAttributes_Closure)
                 (const UpdateListAttributes *message,
                  void *closure_data);
typedef void (*Op_Closure)
                 (const Op *message,
                  void *closure_data);
typedef void (*OpList_Closure)
                 (const OpList *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor add__descriptor;
extern const ProtobufCMessageDescriptor rem__descriptor;
extern const ProtobufCMessageDescriptor mov__descriptor;
extern const ProtobufCMessageDescriptor item_attributes_partial_state__descriptor;
extern const ProtobufCEnumDescriptor    item_attributes_partial_state__item_attribute_kind__descriptor;
extern const ProtobufCMessageDescriptor list_attributes_partial_state__descriptor;
extern const ProtobufCEnumDescriptor    list_attributes_partial_state__list_attribute_kind__descriptor;
extern const ProtobufCMessageDescriptor update_item_attributes__descriptor;
extern const ProtobufCMessageDescriptor update_list_attributes__descriptor;
extern const ProtobufCMessageDescriptor op__descriptor;
extern const ProtobufCEnumDescriptor    op__kind__descriptor;
extern const ProtobufCMessageDescriptor op_list__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_playlist4ops_2eproto__INCLUDED */
