/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: playlist4ops.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "playlist4ops.pb-c.h"
void   add__init
                     (Add         *message)
{
  static const Add init_value = ADD__INIT;
  *message = init_value;
}
size_t add__get_packed_size
                     (const Add *message)
{
  assert(message->base.descriptor == &add__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t add__pack
                     (const Add *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &add__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t add__pack_to_buffer
                     (const Add *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &add__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Add *
       add__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Add *)
     protobuf_c_message_unpack (&add__descriptor,
                                allocator, len, data);
}
void   add__free_unpacked
                     (Add *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &add__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rem__init
                     (Rem         *message)
{
  static const Rem init_value = REM__INIT;
  *message = init_value;
}
size_t rem__get_packed_size
                     (const Rem *message)
{
  assert(message->base.descriptor == &rem__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rem__pack
                     (const Rem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rem__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rem__pack_to_buffer
                     (const Rem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rem__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rem *
       rem__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rem *)
     protobuf_c_message_unpack (&rem__descriptor,
                                allocator, len, data);
}
void   rem__free_unpacked
                     (Rem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rem__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mov__init
                     (Mov         *message)
{
  static const Mov init_value = MOV__INIT;
  *message = init_value;
}
size_t mov__get_packed_size
                     (const Mov *message)
{
  assert(message->base.descriptor == &mov__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mov__pack
                     (const Mov *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mov__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mov__pack_to_buffer
                     (const Mov *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mov__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mov *
       mov__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mov *)
     protobuf_c_message_unpack (&mov__descriptor,
                                allocator, len, data);
}
void   mov__free_unpacked
                     (Mov *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mov__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   item_attributes_partial_state__init
                     (ItemAttributesPartialState         *message)
{
  static const ItemAttributesPartialState init_value = ITEM_ATTRIBUTES_PARTIAL_STATE__INIT;
  *message = init_value;
}
size_t item_attributes_partial_state__get_packed_size
                     (const ItemAttributesPartialState *message)
{
  assert(message->base.descriptor == &item_attributes_partial_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t item_attributes_partial_state__pack
                     (const ItemAttributesPartialState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &item_attributes_partial_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t item_attributes_partial_state__pack_to_buffer
                     (const ItemAttributesPartialState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &item_attributes_partial_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ItemAttributesPartialState *
       item_attributes_partial_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ItemAttributesPartialState *)
     protobuf_c_message_unpack (&item_attributes_partial_state__descriptor,
                                allocator, len, data);
}
void   item_attributes_partial_state__free_unpacked
                     (ItemAttributesPartialState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &item_attributes_partial_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   list_attributes_partial_state__init
                     (ListAttributesPartialState         *message)
{
  static const ListAttributesPartialState init_value = LIST_ATTRIBUTES_PARTIAL_STATE__INIT;
  *message = init_value;
}
size_t list_attributes_partial_state__get_packed_size
                     (const ListAttributesPartialState *message)
{
  assert(message->base.descriptor == &list_attributes_partial_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t list_attributes_partial_state__pack
                     (const ListAttributesPartialState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &list_attributes_partial_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t list_attributes_partial_state__pack_to_buffer
                     (const ListAttributesPartialState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &list_attributes_partial_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ListAttributesPartialState *
       list_attributes_partial_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ListAttributesPartialState *)
     protobuf_c_message_unpack (&list_attributes_partial_state__descriptor,
                                allocator, len, data);
}
void   list_attributes_partial_state__free_unpacked
                     (ListAttributesPartialState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &list_attributes_partial_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   update_item_attributes__init
                     (UpdateItemAttributes         *message)
{
  static const UpdateItemAttributes init_value = UPDATE_ITEM_ATTRIBUTES__INIT;
  *message = init_value;
}
size_t update_item_attributes__get_packed_size
                     (const UpdateItemAttributes *message)
{
  assert(message->base.descriptor == &update_item_attributes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t update_item_attributes__pack
                     (const UpdateItemAttributes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &update_item_attributes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t update_item_attributes__pack_to_buffer
                     (const UpdateItemAttributes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &update_item_attributes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UpdateItemAttributes *
       update_item_attributes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UpdateItemAttributes *)
     protobuf_c_message_unpack (&update_item_attributes__descriptor,
                                allocator, len, data);
}
void   update_item_attributes__free_unpacked
                     (UpdateItemAttributes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &update_item_attributes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   update_list_attributes__init
                     (UpdateListAttributes         *message)
{
  static const UpdateListAttributes init_value = UPDATE_LIST_ATTRIBUTES__INIT;
  *message = init_value;
}
size_t update_list_attributes__get_packed_size
                     (const UpdateListAttributes *message)
{
  assert(message->base.descriptor == &update_list_attributes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t update_list_attributes__pack
                     (const UpdateListAttributes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &update_list_attributes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t update_list_attributes__pack_to_buffer
                     (const UpdateListAttributes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &update_list_attributes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UpdateListAttributes *
       update_list_attributes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UpdateListAttributes *)
     protobuf_c_message_unpack (&update_list_attributes__descriptor,
                                allocator, len, data);
}
void   update_list_attributes__free_unpacked
                     (UpdateListAttributes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &update_list_attributes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   op__init
                     (Op         *message)
{
  static const Op init_value = OP__INIT;
  *message = init_value;
}
size_t op__get_packed_size
                     (const Op *message)
{
  assert(message->base.descriptor == &op__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t op__pack
                     (const Op *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &op__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t op__pack_to_buffer
                     (const Op *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &op__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Op *
       op__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Op *)
     protobuf_c_message_unpack (&op__descriptor,
                                allocator, len, data);
}
void   op__free_unpacked
                     (Op *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &op__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   op_list__init
                     (OpList         *message)
{
  static const OpList init_value = OP_LIST__INIT;
  *message = init_value;
}
size_t op_list__get_packed_size
                     (const OpList *message)
{
  assert(message->base.descriptor == &op_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t op_list__pack
                     (const OpList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &op_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t op_list__pack_to_buffer
                     (const OpList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &op_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OpList *
       op_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OpList *)
     protobuf_c_message_unpack (&op_list__descriptor,
                                allocator, len, data);
}
void   op_list__free_unpacked
                     (OpList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &op_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor add__field_descriptors[5] =
{
  {
    "fromIndex",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Add, has_fromindex),
    offsetof(Add, fromindex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "items",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Add, n_items),
    offsetof(Add, items),
    &item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "list_checksum",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Add, list_checksum),
    &list_checksum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addLast",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Add, has_addlast),
    offsetof(Add, addlast),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addFirst",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Add, has_addfirst),
    offsetof(Add, addfirst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned add__field_indices_by_name[] = {
  4,   /* field[4] = addFirst */
  3,   /* field[3] = addLast */
  0,   /* field[0] = fromIndex */
  1,   /* field[1] = items */
  2,   /* field[2] = list_checksum */
};
static const ProtobufCIntRange add__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor add__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Add",
  "Add",
  "Add",
  "",
  sizeof(Add),
  5,
  add__field_descriptors,
  add__field_indices_by_name,
  1,  add__number_ranges,
  (ProtobufCMessageInit) add__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rem__field_descriptors[7] =
{
  {
    "fromIndex",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Rem, has_fromindex),
    offsetof(Rem, fromindex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Rem, has_length),
    offsetof(Rem, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "items",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Rem, n_items),
    offsetof(Rem, items),
    &item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "list_checksum",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Rem, list_checksum),
    &list_checksum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "items_checksum",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Rem, items_checksum),
    &list_checksum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uris_checksum",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Rem, uris_checksum),
    &list_checksum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "itemsAsKey",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Rem, has_itemsaskey),
    offsetof(Rem, itemsaskey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rem__field_indices_by_name[] = {
  0,   /* field[0] = fromIndex */
  2,   /* field[2] = items */
  6,   /* field[6] = itemsAsKey */
  4,   /* field[4] = items_checksum */
  1,   /* field[1] = length */
  3,   /* field[3] = list_checksum */
  5,   /* field[5] = uris_checksum */
};
static const ProtobufCIntRange rem__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor rem__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rem",
  "Rem",
  "Rem",
  "",
  sizeof(Rem),
  7,
  rem__field_descriptors,
  rem__field_indices_by_name,
  1,  rem__number_ranges,
  (ProtobufCMessageInit) rem__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mov__field_descriptors[6] =
{
  {
    "fromIndex",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Mov, has_fromindex),
    offsetof(Mov, fromindex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Mov, has_length),
    offsetof(Mov, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "toIndex",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Mov, has_toindex),
    offsetof(Mov, toindex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "list_checksum",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Mov, list_checksum),
    &list_checksum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "items_checksum",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Mov, items_checksum),
    &list_checksum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uris_checksum",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Mov, uris_checksum),
    &list_checksum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mov__field_indices_by_name[] = {
  0,   /* field[0] = fromIndex */
  4,   /* field[4] = items_checksum */
  1,   /* field[1] = length */
  3,   /* field[3] = list_checksum */
  2,   /* field[2] = toIndex */
  5,   /* field[5] = uris_checksum */
};
static const ProtobufCIntRange mov__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor mov__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Mov",
  "Mov",
  "Mov",
  "",
  sizeof(Mov),
  6,
  mov__field_descriptors,
  mov__field_indices_by_name,
  1,  mov__number_ranges,
  (ProtobufCMessageInit) mov__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue item_attributes_partial_state__item_attribute_kind__enum_values_by_number[11] =
{
  { "ITEM_UNKNOWN", "ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_UNKNOWN", 0 },
  { "ITEM_ADDED_BY", "ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_ADDED_BY", 1 },
  { "ITEM_TIMESTAMP", "ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_TIMESTAMP", 2 },
  { "ITEM_MESSAGE", "ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_MESSAGE", 3 },
  { "ITEM_SEEN", "ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_SEEN", 4 },
  { "ITEM_DOWNLOAD_COUNT", "ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_DOWNLOAD_COUNT", 5 },
  { "ITEM_DOWNLOAD_FORMAT", "ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_DOWNLOAD_FORMAT", 6 },
  { "ITEM_SEVENDIGITAL_ID", "ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_SEVENDIGITAL_ID", 7 },
  { "ITEM_SEVENDIGITAL_LEFT", "ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_SEVENDIGITAL_LEFT", 8 },
  { "ITEM_SEEN_AT", "ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_SEEN_AT", 9 },
  { "ITEM_PUBLIC", "ITEM_ATTRIBUTES_PARTIAL_STATE__ITEM_ATTRIBUTE_KIND__ITEM_PUBLIC", 10 },
};
static const ProtobufCIntRange item_attributes_partial_state__item_attribute_kind__value_ranges[] = {
{0, 0},{0, 11}
};
static const ProtobufCEnumValueIndex item_attributes_partial_state__item_attribute_kind__enum_values_by_name[11] =
{
  { "ITEM_ADDED_BY", 1 },
  { "ITEM_DOWNLOAD_COUNT", 5 },
  { "ITEM_DOWNLOAD_FORMAT", 6 },
  { "ITEM_MESSAGE", 3 },
  { "ITEM_PUBLIC", 10 },
  { "ITEM_SEEN", 4 },
  { "ITEM_SEEN_AT", 9 },
  { "ITEM_SEVENDIGITAL_ID", 7 },
  { "ITEM_SEVENDIGITAL_LEFT", 8 },
  { "ITEM_TIMESTAMP", 2 },
  { "ITEM_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor item_attributes_partial_state__item_attribute_kind__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ItemAttributesPartialState.ItemAttributeKind",
  "ItemAttributeKind",
  "ItemAttributesPartialState__ItemAttributeKind",
  "",
  11,
  item_attributes_partial_state__item_attribute_kind__enum_values_by_number,
  11,
  item_attributes_partial_state__item_attribute_kind__enum_values_by_name,
  1,
  item_attributes_partial_state__item_attribute_kind__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor item_attributes_partial_state__field_descriptors[2] =
{
  {
    "values",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ItemAttributesPartialState, values),
    &item_attributes__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no_value",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ItemAttributesPartialState, n_no_value),
    offsetof(ItemAttributesPartialState, no_value),
    &item_attributes_partial_state__item_attribute_kind__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned item_attributes_partial_state__field_indices_by_name[] = {
  1,   /* field[1] = no_value */
  0,   /* field[0] = values */
};
static const ProtobufCIntRange item_attributes_partial_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor item_attributes_partial_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ItemAttributesPartialState",
  "ItemAttributesPartialState",
  "ItemAttributesPartialState",
  "",
  sizeof(ItemAttributesPartialState),
  2,
  item_attributes_partial_state__field_descriptors,
  item_attributes_partial_state__field_indices_by_name,
  1,  item_attributes_partial_state__number_ranges,
  (ProtobufCMessageInit) item_attributes_partial_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue list_attributes_partial_state__list_attribute_kind__enum_values_by_number[8] =
{
  { "LIST_UNKNOWN", "LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND__LIST_UNKNOWN", 0 },
  { "LIST_NAME", "LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND__LIST_NAME", 1 },
  { "LIST_DESCRIPTION", "LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND__LIST_DESCRIPTION", 2 },
  { "LIST_PICTURE", "LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND__LIST_PICTURE", 3 },
  { "LIST_COLLABORATIVE", "LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND__LIST_COLLABORATIVE", 4 },
  { "LIST_PL3_VERSION", "LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND__LIST_PL3_VERSION", 5 },
  { "LIST_DELETED_BY_OWNER", "LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND__LIST_DELETED_BY_OWNER", 6 },
  { "LIST_RESTRICTED_COLLABORATIVE", "LIST_ATTRIBUTES_PARTIAL_STATE__LIST_ATTRIBUTE_KIND__LIST_RESTRICTED_COLLABORATIVE", 7 },
};
static const ProtobufCIntRange list_attributes_partial_state__list_attribute_kind__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex list_attributes_partial_state__list_attribute_kind__enum_values_by_name[8] =
{
  { "LIST_COLLABORATIVE", 4 },
  { "LIST_DELETED_BY_OWNER", 6 },
  { "LIST_DESCRIPTION", 2 },
  { "LIST_NAME", 1 },
  { "LIST_PICTURE", 3 },
  { "LIST_PL3_VERSION", 5 },
  { "LIST_RESTRICTED_COLLABORATIVE", 7 },
  { "LIST_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor list_attributes_partial_state__list_attribute_kind__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ListAttributesPartialState.ListAttributeKind",
  "ListAttributeKind",
  "ListAttributesPartialState__ListAttributeKind",
  "",
  8,
  list_attributes_partial_state__list_attribute_kind__enum_values_by_number,
  8,
  list_attributes_partial_state__list_attribute_kind__enum_values_by_name,
  1,
  list_attributes_partial_state__list_attribute_kind__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor list_attributes_partial_state__field_descriptors[2] =
{
  {
    "values",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ListAttributesPartialState, values),
    &list_attributes__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no_value",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ListAttributesPartialState, n_no_value),
    offsetof(ListAttributesPartialState, no_value),
    &list_attributes_partial_state__list_attribute_kind__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned list_attributes_partial_state__field_indices_by_name[] = {
  1,   /* field[1] = no_value */
  0,   /* field[0] = values */
};
static const ProtobufCIntRange list_attributes_partial_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor list_attributes_partial_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ListAttributesPartialState",
  "ListAttributesPartialState",
  "ListAttributesPartialState",
  "",
  sizeof(ListAttributesPartialState),
  2,
  list_attributes_partial_state__field_descriptors,
  list_attributes_partial_state__field_indices_by_name,
  1,  list_attributes_partial_state__number_ranges,
  (ProtobufCMessageInit) list_attributes_partial_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor update_item_attributes__field_descriptors[5] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(UpdateItemAttributes, has_index),
    offsetof(UpdateItemAttributes, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_attributes",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UpdateItemAttributes, new_attributes),
    &item_attributes_partial_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "old_attributes",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UpdateItemAttributes, old_attributes),
    &item_attributes_partial_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "list_checksum",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UpdateItemAttributes, list_checksum),
    &list_checksum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "old_attributes_checksum",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UpdateItemAttributes, old_attributes_checksum),
    &list_checksum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned update_item_attributes__field_indices_by_name[] = {
  0,   /* field[0] = index */
  3,   /* field[3] = list_checksum */
  1,   /* field[1] = new_attributes */
  2,   /* field[2] = old_attributes */
  4,   /* field[4] = old_attributes_checksum */
};
static const ProtobufCIntRange update_item_attributes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor update_item_attributes__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UpdateItemAttributes",
  "UpdateItemAttributes",
  "UpdateItemAttributes",
  "",
  sizeof(UpdateItemAttributes),
  5,
  update_item_attributes__field_descriptors,
  update_item_attributes__field_indices_by_name,
  1,  update_item_attributes__number_ranges,
  (ProtobufCMessageInit) update_item_attributes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor update_list_attributes__field_descriptors[4] =
{
  {
    "new_attributes",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UpdateListAttributes, new_attributes),
    &list_attributes_partial_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "old_attributes",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UpdateListAttributes, old_attributes),
    &list_attributes_partial_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "list_checksum",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UpdateListAttributes, list_checksum),
    &list_checksum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "old_attributes_checksum",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UpdateListAttributes, old_attributes_checksum),
    &list_checksum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned update_list_attributes__field_indices_by_name[] = {
  2,   /* field[2] = list_checksum */
  0,   /* field[0] = new_attributes */
  1,   /* field[1] = old_attributes */
  3,   /* field[3] = old_attributes_checksum */
};
static const ProtobufCIntRange update_list_attributes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor update_list_attributes__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UpdateListAttributes",
  "UpdateListAttributes",
  "UpdateListAttributes",
  "",
  sizeof(UpdateListAttributes),
  4,
  update_list_attributes__field_descriptors,
  update_list_attributes__field_indices_by_name,
  1,  update_list_attributes__number_ranges,
  (ProtobufCMessageInit) update_list_attributes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue op__kind__enum_values_by_number[6] =
{
  { "KIND_UNKNOWN", "OP__KIND__KIND_UNKNOWN", 0 },
  { "ADD", "OP__KIND__ADD", 2 },
  { "REM", "OP__KIND__REM", 3 },
  { "MOV", "OP__KIND__MOV", 4 },
  { "UPDATE_ITEM_ATTRIBUTES", "OP__KIND__UPDATE_ITEM_ATTRIBUTES", 5 },
  { "UPDATE_LIST_ATTRIBUTES", "OP__KIND__UPDATE_LIST_ATTRIBUTES", 6 },
};
static const ProtobufCIntRange op__kind__value_ranges[] = {
{0, 0},{2, 1},{0, 6}
};
static const ProtobufCEnumValueIndex op__kind__enum_values_by_name[6] =
{
  { "ADD", 1 },
  { "KIND_UNKNOWN", 0 },
  { "MOV", 3 },
  { "REM", 2 },
  { "UPDATE_ITEM_ATTRIBUTES", 4 },
  { "UPDATE_LIST_ATTRIBUTES", 5 },
};
const ProtobufCEnumDescriptor op__kind__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Op.Kind",
  "Kind",
  "Op__Kind",
  "",
  6,
  op__kind__enum_values_by_number,
  6,
  op__kind__enum_values_by_name,
  2,
  op__kind__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor op__field_descriptors[6] =
{
  {
    "kind",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Op, has_kind),
    offsetof(Op, kind),
    &op__kind__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Op, add),
    &add__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rem",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Op, rem),
    &rem__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mov",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Op, mov),
    &mov__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update_item_attributes",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Op, update_item_attributes),
    &update_item_attributes__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update_list_attributes",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Op, update_list_attributes),
    &update_list_attributes__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned op__field_indices_by_name[] = {
  1,   /* field[1] = add */
  0,   /* field[0] = kind */
  3,   /* field[3] = mov */
  2,   /* field[2] = rem */
  4,   /* field[4] = update_item_attributes */
  5,   /* field[5] = update_list_attributes */
};
static const ProtobufCIntRange op__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor op__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Op",
  "Op",
  "Op",
  "",
  sizeof(Op),
  6,
  op__field_descriptors,
  op__field_indices_by_name,
  1,  op__number_ranges,
  (ProtobufCMessageInit) op__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor op_list__field_descriptors[1] =
{
  {
    "ops",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpList, n_ops),
    offsetof(OpList, ops),
    &op__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned op_list__field_indices_by_name[] = {
  0,   /* field[0] = ops */
};
static const ProtobufCIntRange op_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor op_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OpList",
  "OpList",
  "OpList",
  "",
  sizeof(OpList),
  1,
  op_list__field_descriptors,
  op_list__field_indices_by_name,
  1,  op_list__number_ranges,
  (ProtobufCMessageInit) op_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
