/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: playlist4issues.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "playlist4issues.pb-c.h"
void   client_issue__init
                     (ClientIssue         *message)
{
  static const ClientIssue init_value = CLIENT_ISSUE__INIT;
  *message = init_value;
}
size_t client_issue__get_packed_size
                     (const ClientIssue *message)
{
  assert(message->base.descriptor == &client_issue__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_issue__pack
                     (const ClientIssue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_issue__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_issue__pack_to_buffer
                     (const ClientIssue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_issue__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientIssue *
       client_issue__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientIssue *)
     protobuf_c_message_unpack (&client_issue__descriptor,
                                allocator, len, data);
}
void   client_issue__free_unpacked
                     (ClientIssue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_issue__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_resolve_action__init
                     (ClientResolveAction         *message)
{
  static const ClientResolveAction init_value = CLIENT_RESOLVE_ACTION__INIT;
  *message = init_value;
}
size_t client_resolve_action__get_packed_size
                     (const ClientResolveAction *message)
{
  assert(message->base.descriptor == &client_resolve_action__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_resolve_action__pack
                     (const ClientResolveAction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_resolve_action__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_resolve_action__pack_to_buffer
                     (const ClientResolveAction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_resolve_action__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientResolveAction *
       client_resolve_action__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientResolveAction *)
     protobuf_c_message_unpack (&client_resolve_action__descriptor,
                                allocator, len, data);
}
void   client_resolve_action__free_unpacked
                     (ClientResolveAction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_resolve_action__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue client_issue__level__enum_values_by_number[6] =
{
  { "LEVEL_UNKNOWN", "CLIENT_ISSUE__LEVEL__LEVEL_UNKNOWN", 0 },
  { "LEVEL_DEBUG", "CLIENT_ISSUE__LEVEL__LEVEL_DEBUG", 1 },
  { "LEVEL_INFO", "CLIENT_ISSUE__LEVEL__LEVEL_INFO", 2 },
  { "LEVEL_NOTICE", "CLIENT_ISSUE__LEVEL__LEVEL_NOTICE", 3 },
  { "LEVEL_WARNING", "CLIENT_ISSUE__LEVEL__LEVEL_WARNING", 4 },
  { "LEVEL_ERROR", "CLIENT_ISSUE__LEVEL__LEVEL_ERROR", 5 },
};
static const ProtobufCIntRange client_issue__level__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex client_issue__level__enum_values_by_name[6] =
{
  { "LEVEL_DEBUG", 1 },
  { "LEVEL_ERROR", 5 },
  { "LEVEL_INFO", 2 },
  { "LEVEL_NOTICE", 3 },
  { "LEVEL_UNKNOWN", 0 },
  { "LEVEL_WARNING", 4 },
};
const ProtobufCEnumDescriptor client_issue__level__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ClientIssue.Level",
  "Level",
  "ClientIssue__Level",
  "",
  6,
  client_issue__level__enum_values_by_number,
  6,
  client_issue__level__enum_values_by_name,
  1,
  client_issue__level__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue client_issue__code__enum_values_by_number[6] =
{
  { "CODE_UNKNOWN", "CLIENT_ISSUE__CODE__CODE_UNKNOWN", 0 },
  { "CODE_INDEX_OUT_OF_BOUNDS", "CLIENT_ISSUE__CODE__CODE_INDEX_OUT_OF_BOUNDS", 1 },
  { "CODE_VERSION_MISMATCH", "CLIENT_ISSUE__CODE__CODE_VERSION_MISMATCH", 2 },
  { "CODE_CACHED_CHANGE", "CLIENT_ISSUE__CODE__CODE_CACHED_CHANGE", 3 },
  { "CODE_OFFLINE_CHANGE", "CLIENT_ISSUE__CODE__CODE_OFFLINE_CHANGE", 4 },
  { "CODE_CONCURRENT_CHANGE", "CLIENT_ISSUE__CODE__CODE_CONCURRENT_CHANGE", 5 },
};
static const ProtobufCIntRange client_issue__code__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex client_issue__code__enum_values_by_name[6] =
{
  { "CODE_CACHED_CHANGE", 3 },
  { "CODE_CONCURRENT_CHANGE", 5 },
  { "CODE_INDEX_OUT_OF_BOUNDS", 1 },
  { "CODE_OFFLINE_CHANGE", 4 },
  { "CODE_UNKNOWN", 0 },
  { "CODE_VERSION_MISMATCH", 2 },
};
const ProtobufCEnumDescriptor client_issue__code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ClientIssue.Code",
  "Code",
  "ClientIssue__Code",
  "",
  6,
  client_issue__code__enum_values_by_number,
  6,
  client_issue__code__enum_values_by_name,
  1,
  client_issue__code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor client_issue__field_descriptors[3] =
{
  {
    "level",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ClientIssue, has_level),
    offsetof(ClientIssue, level),
    &client_issue__level__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ClientIssue, has_code),
    offsetof(ClientIssue, code),
    &client_issue__code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "repeatCount",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ClientIssue, has_repeatcount),
    offsetof(ClientIssue, repeatcount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_issue__field_indices_by_name[] = {
  1,   /* field[1] = code */
  0,   /* field[0] = level */
  2,   /* field[2] = repeatCount */
};
static const ProtobufCIntRange client_issue__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor client_issue__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientIssue",
  "ClientIssue",
  "ClientIssue",
  "",
  sizeof(ClientIssue),
  3,
  client_issue__field_descriptors,
  client_issue__field_indices_by_name,
  1,  client_issue__number_ranges,
  (ProtobufCMessageInit) client_issue__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue client_resolve_action__code__enum_values_by_number[7] =
{
  { "CODE_UNKNOWN", "CLIENT_RESOLVE_ACTION__CODE__CODE_UNKNOWN", 0 },
  { "CODE_NO_ACTION", "CLIENT_RESOLVE_ACTION__CODE__CODE_NO_ACTION", 1 },
  { "CODE_RETRY", "CLIENT_RESOLVE_ACTION__CODE__CODE_RETRY", 2 },
  { "CODE_RELOAD", "CLIENT_RESOLVE_ACTION__CODE__CODE_RELOAD", 3 },
  { "CODE_DISCARD_LOCAL_CHANGES", "CLIENT_RESOLVE_ACTION__CODE__CODE_DISCARD_LOCAL_CHANGES", 4 },
  { "CODE_SEND_DUMP", "CLIENT_RESOLVE_ACTION__CODE__CODE_SEND_DUMP", 5 },
  { "CODE_DISPLAY_ERROR_MESSAGE", "CLIENT_RESOLVE_ACTION__CODE__CODE_DISPLAY_ERROR_MESSAGE", 6 },
};
static const ProtobufCIntRange client_resolve_action__code__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex client_resolve_action__code__enum_values_by_name[7] =
{
  { "CODE_DISCARD_LOCAL_CHANGES", 4 },
  { "CODE_DISPLAY_ERROR_MESSAGE", 6 },
  { "CODE_NO_ACTION", 1 },
  { "CODE_RELOAD", 3 },
  { "CODE_RETRY", 2 },
  { "CODE_SEND_DUMP", 5 },
  { "CODE_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor client_resolve_action__code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ClientResolveAction.Code",
  "Code",
  "ClientResolveAction__Code",
  "",
  7,
  client_resolve_action__code__enum_values_by_number,
  7,
  client_resolve_action__code__enum_values_by_name,
  1,
  client_resolve_action__code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue client_resolve_action__initiator__enum_values_by_number[3] =
{
  { "INITIATOR_UNKNOWN", "CLIENT_RESOLVE_ACTION__INITIATOR__INITIATOR_UNKNOWN", 0 },
  { "INITIATOR_SERVER", "CLIENT_RESOLVE_ACTION__INITIATOR__INITIATOR_SERVER", 1 },
  { "INITIATOR_CLIENT", "CLIENT_RESOLVE_ACTION__INITIATOR__INITIATOR_CLIENT", 2 },
};
static const ProtobufCIntRange client_resolve_action__initiator__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex client_resolve_action__initiator__enum_values_by_name[3] =
{
  { "INITIATOR_CLIENT", 2 },
  { "INITIATOR_SERVER", 1 },
  { "INITIATOR_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor client_resolve_action__initiator__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ClientResolveAction.Initiator",
  "Initiator",
  "ClientResolveAction__Initiator",
  "",
  3,
  client_resolve_action__initiator__enum_values_by_number,
  3,
  client_resolve_action__initiator__enum_values_by_name,
  1,
  client_resolve_action__initiator__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor client_resolve_action__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ClientResolveAction, has_code),
    offsetof(ClientResolveAction, code),
    &client_resolve_action__code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "initiator",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ClientResolveAction, has_initiator),
    offsetof(ClientResolveAction, initiator),
    &client_resolve_action__initiator__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_resolve_action__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = initiator */
};
static const ProtobufCIntRange client_resolve_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor client_resolve_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientResolveAction",
  "ClientResolveAction",
  "ClientResolveAction",
  "",
  sizeof(ClientResolveAction),
  2,
  client_resolve_action__field_descriptors,
  client_resolve_action__field_indices_by_name,
  1,  client_resolve_action__number_ranges,
  (ProtobufCMessageInit) client_resolve_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
