/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: playlist4meta.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "playlist4meta.pb-c.h"
void   list_checksum__init
                     (ListChecksum         *message)
{
  static const ListChecksum init_value = LIST_CHECKSUM__INIT;
  *message = init_value;
}
size_t list_checksum__get_packed_size
                     (const ListChecksum *message)
{
  assert(message->base.descriptor == &list_checksum__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t list_checksum__pack
                     (const ListChecksum *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &list_checksum__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t list_checksum__pack_to_buffer
                     (const ListChecksum *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &list_checksum__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ListChecksum *
       list_checksum__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ListChecksum *)
     protobuf_c_message_unpack (&list_checksum__descriptor,
                                allocator, len, data);
}
void   list_checksum__free_unpacked
                     (ListChecksum *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &list_checksum__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   download_format__init
                     (DownloadFormat         *message)
{
  static const DownloadFormat init_value = DOWNLOAD_FORMAT__INIT;
  *message = init_value;
}
size_t download_format__get_packed_size
                     (const DownloadFormat *message)
{
  assert(message->base.descriptor == &download_format__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t download_format__pack
                     (const DownloadFormat *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &download_format__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t download_format__pack_to_buffer
                     (const DownloadFormat *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &download_format__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DownloadFormat *
       download_format__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DownloadFormat *)
     protobuf_c_message_unpack (&download_format__descriptor,
                                allocator, len, data);
}
void   download_format__free_unpacked
                     (DownloadFormat *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &download_format__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   list_attributes__init
                     (ListAttributes         *message)
{
  static const ListAttributes init_value = LIST_ATTRIBUTES__INIT;
  *message = init_value;
}
size_t list_attributes__get_packed_size
                     (const ListAttributes *message)
{
  assert(message->base.descriptor == &list_attributes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t list_attributes__pack
                     (const ListAttributes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &list_attributes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t list_attributes__pack_to_buffer
                     (const ListAttributes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &list_attributes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ListAttributes *
       list_attributes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ListAttributes *)
     protobuf_c_message_unpack (&list_attributes__descriptor,
                                allocator, len, data);
}
void   list_attributes__free_unpacked
                     (ListAttributes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &list_attributes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   item_attributes__init
                     (ItemAttributes         *message)
{
  static const ItemAttributes init_value = ITEM_ATTRIBUTES__INIT;
  *message = init_value;
}
size_t item_attributes__get_packed_size
                     (const ItemAttributes *message)
{
  assert(message->base.descriptor == &item_attributes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t item_attributes__pack
                     (const ItemAttributes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &item_attributes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t item_attributes__pack_to_buffer
                     (const ItemAttributes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &item_attributes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ItemAttributes *
       item_attributes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ItemAttributes *)
     protobuf_c_message_unpack (&item_attributes__descriptor,
                                allocator, len, data);
}
void   item_attributes__free_unpacked
                     (ItemAttributes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &item_attributes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   string_attribute__init
                     (StringAttribute         *message)
{
  static const StringAttribute init_value = STRING_ATTRIBUTE__INIT;
  *message = init_value;
}
size_t string_attribute__get_packed_size
                     (const StringAttribute *message)
{
  assert(message->base.descriptor == &string_attribute__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t string_attribute__pack
                     (const StringAttribute *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &string_attribute__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t string_attribute__pack_to_buffer
                     (const StringAttribute *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &string_attribute__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StringAttribute *
       string_attribute__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StringAttribute *)
     protobuf_c_message_unpack (&string_attribute__descriptor,
                                allocator, len, data);
}
void   string_attribute__free_unpacked
                     (StringAttribute *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &string_attribute__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   string_attributes__init
                     (StringAttributes         *message)
{
  static const StringAttributes init_value = STRING_ATTRIBUTES__INIT;
  *message = init_value;
}
size_t string_attributes__get_packed_size
                     (const StringAttributes *message)
{
  assert(message->base.descriptor == &string_attributes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t string_attributes__pack
                     (const StringAttributes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &string_attributes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t string_attributes__pack_to_buffer
                     (const StringAttributes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &string_attributes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StringAttributes *
       string_attributes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StringAttributes *)
     protobuf_c_message_unpack (&string_attributes__descriptor,
                                allocator, len, data);
}
void   string_attributes__free_unpacked
                     (StringAttributes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &string_attributes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor list_checksum__field_descriptors[2] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ListChecksum, has_version),
    offsetof(ListChecksum, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sha1",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ListChecksum, has_sha1),
    offsetof(ListChecksum, sha1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned list_checksum__field_indices_by_name[] = {
  1,   /* field[1] = sha1 */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange list_checksum__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor list_checksum__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ListChecksum",
  "ListChecksum",
  "ListChecksum",
  "",
  sizeof(ListChecksum),
  2,
  list_checksum__field_descriptors,
  list_checksum__field_indices_by_name,
  2,  list_checksum__number_ranges,
  (ProtobufCMessageInit) list_checksum__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue download_format__codec__enum_values_by_number[4] =
{
  { "CODEC_UNKNOWN", "DOWNLOAD_FORMAT__CODEC__CODEC_UNKNOWN", 0 },
  { "OGG_VORBIS", "DOWNLOAD_FORMAT__CODEC__OGG_VORBIS", 1 },
  { "FLAC", "DOWNLOAD_FORMAT__CODEC__FLAC", 2 },
  { "MPEG_1_LAYER_3", "DOWNLOAD_FORMAT__CODEC__MPEG_1_LAYER_3", 3 },
};
static const ProtobufCIntRange download_format__codec__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex download_format__codec__enum_values_by_name[4] =
{
  { "CODEC_UNKNOWN", 0 },
  { "FLAC", 2 },
  { "MPEG_1_LAYER_3", 3 },
  { "OGG_VORBIS", 1 },
};
const ProtobufCEnumDescriptor download_format__codec__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DownloadFormat.Codec",
  "Codec",
  "DownloadFormat__Codec",
  "",
  4,
  download_format__codec__enum_values_by_number,
  4,
  download_format__codec__enum_values_by_name,
  1,
  download_format__codec__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor download_format__field_descriptors[1] =
{
  {
    "codec",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(DownloadFormat, has_codec),
    offsetof(DownloadFormat, codec),
    &download_format__codec__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned download_format__field_indices_by_name[] = {
  0,   /* field[0] = codec */
};
static const ProtobufCIntRange download_format__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor download_format__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DownloadFormat",
  "DownloadFormat",
  "DownloadFormat",
  "",
  sizeof(DownloadFormat),
  1,
  download_format__field_descriptors,
  download_format__field_indices_by_name,
  1,  download_format__number_ranges,
  (ProtobufCMessageInit) download_format__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor list_attributes__field_descriptors[10] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ListAttributes, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ListAttributes, description),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "picture",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ListAttributes, has_picture),
    offsetof(ListAttributes, picture),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "collaborative",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ListAttributes, has_collaborative),
    offsetof(ListAttributes, collaborative),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pl3_version",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ListAttributes, pl3_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deleted_by_owner",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ListAttributes, has_deleted_by_owner),
    offsetof(ListAttributes, deleted_by_owner),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "restricted_collaborative",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ListAttributes, has_restricted_collaborative),
    offsetof(ListAttributes, restricted_collaborative),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deprecated_client_id",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ListAttributes, has_deprecated_client_id),
    offsetof(ListAttributes, deprecated_client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_starred",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ListAttributes, has_public_starred),
    offsetof(ListAttributes, public_starred),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_id",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ListAttributes, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned list_attributes__field_indices_by_name[] = {
  9,   /* field[9] = client_id */
  3,   /* field[3] = collaborative */
  5,   /* field[5] = deleted_by_owner */
  7,   /* field[7] = deprecated_client_id */
  1,   /* field[1] = description */
  0,   /* field[0] = name */
  2,   /* field[2] = picture */
  4,   /* field[4] = pl3_version */
  8,   /* field[8] = public_starred */
  6,   /* field[6] = restricted_collaborative */
};
static const ProtobufCIntRange list_attributes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor list_attributes__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ListAttributes",
  "ListAttributes",
  "ListAttributes",
  "",
  sizeof(ListAttributes),
  10,
  list_attributes__field_descriptors,
  list_attributes__field_indices_by_name,
  1,  list_attributes__number_ranges,
  (ProtobufCMessageInit) list_attributes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor item_attributes__field_descriptors[10] =
{
  {
    "added_by",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ItemAttributes, added_by),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ItemAttributes, has_timestamp),
    offsetof(ItemAttributes, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ItemAttributes, message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seen",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ItemAttributes, has_seen),
    offsetof(ItemAttributes, seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "download_count",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ItemAttributes, has_download_count),
    offsetof(ItemAttributes, download_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "download_format",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ItemAttributes, download_format),
    &download_format__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sevendigital_id",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ItemAttributes, sevendigital_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sevendigital_left",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ItemAttributes, has_sevendigital_left),
    offsetof(ItemAttributes, sevendigital_left),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seen_at",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ItemAttributes, has_seen_at),
    offsetof(ItemAttributes, seen_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ItemAttributes, has_public_),
    offsetof(ItemAttributes, public_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned item_attributes__field_indices_by_name[] = {
  0,   /* field[0] = added_by */
  4,   /* field[4] = download_count */
  5,   /* field[5] = download_format */
  2,   /* field[2] = message */
  9,   /* field[9] = public */
  3,   /* field[3] = seen */
  8,   /* field[8] = seen_at */
  6,   /* field[6] = sevendigital_id */
  7,   /* field[7] = sevendigital_left */
  1,   /* field[1] = timestamp */
};
static const ProtobufCIntRange item_attributes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor item_attributes__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ItemAttributes",
  "ItemAttributes",
  "ItemAttributes",
  "",
  sizeof(ItemAttributes),
  10,
  item_attributes__field_descriptors,
  item_attributes__field_indices_by_name,
  1,  item_attributes__number_ranges,
  (ProtobufCMessageInit) item_attributes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor string_attribute__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StringAttribute, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StringAttribute, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned string_attribute__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange string_attribute__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor string_attribute__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StringAttribute",
  "StringAttribute",
  "StringAttribute",
  "",
  sizeof(StringAttribute),
  2,
  string_attribute__field_descriptors,
  string_attribute__field_indices_by_name,
  1,  string_attribute__number_ranges,
  (ProtobufCMessageInit) string_attribute__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor string_attributes__field_descriptors[1] =
{
  {
    "attribute",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(StringAttributes, n_attribute),
    offsetof(StringAttributes, attribute),
    &string_attribute__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned string_attributes__field_indices_by_name[] = {
  0,   /* field[0] = attribute */
};
static const ProtobufCIntRange string_attributes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor string_attributes__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StringAttributes",
  "StringAttributes",
  "StringAttributes",
  "",
  sizeof(StringAttributes),
  1,
  string_attributes__field_descriptors,
  string_attributes__field_indices_by_name,
  1,  string_attributes__number_ranges,
  (ProtobufCMessageInit) string_attributes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
